// noinspection SpellCheckingInspection
/**
 * Auto-generated TypeScript types for Wire system contracts.
 * Generated by generate-sysio-contract-types.py
 *
 * Property naming style: snake
 */

/** Extended asset type. */
export interface ExtendedAsset {
  quantity: string
  contract: string
}

// ── sysio.authex ──

/** sysio.authex::ChainKind (enum, int32) */
export enum SysioAuthexChainkind {
  CHAIN_KIND_UNKNOWN = 0,
  CHAIN_KIND_WIRE = 1,
  CHAIN_KIND_EVM = 2,
  CHAIN_KIND_SVM = 3,
}

/** sysio.authex::clearlinks (action) */
export interface SysioAuthexClearlinksAction {
}

/** sysio.authex::createlink (action) */
export interface SysioAuthexCreatelinkAction {
  chain_kind: SysioAuthexChainkind | keyof typeof SysioAuthexChainkind
  account: string
  sig: string
  pub_key: string
  nonce: number | string
}

/** sysio.authex::links_key (type) */
export interface SysioAuthexLinksKeyType {
  key: number | string
}

/** sysio.authex::links_s (type) */
export interface SysioAuthexLinksSType {
  key: number | string
  username: string
  chain_kind: SysioAuthexChainkind | keyof typeof SysioAuthexChainkind
  pub_key: string
}

/** sysio.authex::recordlink (action) */
export interface SysioAuthexRecordlinkAction {
  account: string
  chain_kind: SysioAuthexChainkind | keyof typeof SysioAuthexChainkind
  pub_key: string
}

/** sysio.authex - action + table surface for the typed contract client. */
export interface SysioAuthexContract {
  actions: {
    clearlinks: SysioAuthexClearlinksAction
    createlink: SysioAuthexCreatelinkAction
    recordlink: SysioAuthexRecordlinkAction
  }
  tables: {
    links: SysioAuthexLinksSType
  }
}

// ── sysio.bios ──

/** sysio.bios::abi_hash (type) */
export interface SysioBiosAbiHashType {
  owner: string
  hash: string
}

/** sysio.bios::abihash_key (type) */
export interface SysioBiosAbihashKeyType {
  owner: number | string
}

/** sysio.bios::activate (action) */
export interface SysioBiosActivateAction {
  feature_digest: string
}

/** sysio.bios::authority (type) */
export interface SysioBiosAuthorityType {
  threshold: number
  keys: SysioBiosKeyWeightType[]
  accounts: SysioBiosPermissionLevelWeightType[]
}

/** sysio.bios::block_signing_authority_v0 (type) */
export interface SysioBiosBlockSigningAuthorityV0Type {
  threshold: number
  keys: SysioBiosKeyWeightType[]
}

/** sysio.bios::blockchain_parameters (type) */
export interface SysioBiosBlockchainParametersType {
  max_block_net_usage: number | string
  target_block_net_usage_pct: number
  max_transaction_net_usage: number
  net_usage_leeway: number
  context_free_discount_net_usage_num: number
  context_free_discount_net_usage_den: number
  max_block_cpu_usage: number
  target_block_cpu_usage_pct: number
  max_transaction_cpu_usage: number
  min_transaction_cpu_usage: number
  max_transaction_lifetime: number
  max_transaction_delay: number
  max_inline_action_size: number
  max_inline_action_depth: number
  max_authority_depth: number
  max_action_return_value_size: number
  max_kv_key_size: number
  max_kv_value_size: number
  max_kv_secondary_key_size: number
}

/** sysio.bios::deleteauth (action) */
export interface SysioBiosDeleteauthAction {
  account: string
  permission: string
}

/** sysio.bios::finalizer_authority (type) */
export interface SysioBiosFinalizerAuthorityType {
  description: string
  weight: number | string
  public_key: string
  pop: string
}

/** sysio.bios::finalizer_policy (type) */
export interface SysioBiosFinalizerPolicyType {
  threshold: number | string
  finalizers: SysioBiosFinalizerAuthorityType[]
}

/** sysio.bios::key_weight (type) */
export interface SysioBiosKeyWeightType {
  key: string
  weight: number
}

/** sysio.bios::linkauth (action) */
export interface SysioBiosLinkauthAction {
  account: string
  code: string
  type: string
  requirement: string
}

/** sysio.bios::newaccount (action) */
export interface SysioBiosNewaccountAction {
  creator: string
  name: string
  owner: SysioBiosAuthorityType
  active: SysioBiosAuthorityType
}

/** sysio.bios::permission_level (type) */
export interface SysioBiosPermissionLevelType {
  actor: string
  permission: string
}

/** sysio.bios::permission_level_weight (type) */
export interface SysioBiosPermissionLevelWeightType {
  permission: SysioBiosPermissionLevelType
  weight: number
}

/** sysio.bios::producer_authority (type) */
export interface SysioBiosProducerAuthorityType {
  producer_name: string
  authority: unknown
}

/** sysio.bios::producer_key (type) */
export interface SysioBiosProducerKeyType {
  producer_name: string
  block_signing_key: string
}

/** sysio.bios::reqactivated (action) */
export interface SysioBiosReqactivatedAction {
  feature_digest: string
}

/** sysio.bios::reqauth (action) */
export interface SysioBiosReqauthAction {
  from: string
}

/** sysio.bios::setabi (action) */
export interface SysioBiosSetabiAction {
  account: string
  abi: string
}

/** sysio.bios::setalimits (action) */
export interface SysioBiosSetalimitsAction {
  account: string
  ram_bytes: number | string
  net_weight: number | string
  cpu_weight: number | string
}

/** sysio.bios::setcode (action) */
export interface SysioBiosSetcodeAction {
  account: string
  vmtype: number
  vmversion: number
  code: string
}

/** sysio.bios::setfinalizer (action) */
export interface SysioBiosSetfinalizerAction {
  finalizer_policy: SysioBiosFinalizerPolicyType
}

/** sysio.bios::setparams (action) */
export interface SysioBiosSetparamsAction {
  params: SysioBiosBlockchainParametersType
}

/** sysio.bios::setpriv (action) */
export interface SysioBiosSetprivAction {
  account: string
  is_priv: number
}

/** sysio.bios::setprodkeys (action) */
export interface SysioBiosSetprodkeysAction {
  schedule: SysioBiosProducerKeyType[]
}

/** sysio.bios::setprods (action) */
export interface SysioBiosSetprodsAction {
  schedule: SysioBiosProducerAuthorityType[]
}

/** sysio.bios::unlinkauth (action) */
export interface SysioBiosUnlinkauthAction {
  account: string
  code: string
  type: string
}

/** sysio.bios::updateauth (action) */
export interface SysioBiosUpdateauthAction {
  account: string
  permission: string
  parent: string
  auth: SysioBiosAuthorityType
}

/** sysio.bios - action + table surface for the typed contract client. */
export interface SysioBiosContract {
  actions: {
    activate: SysioBiosActivateAction
    deleteauth: SysioBiosDeleteauthAction
    linkauth: SysioBiosLinkauthAction
    newaccount: SysioBiosNewaccountAction
    reqactivated: SysioBiosReqactivatedAction
    reqauth: SysioBiosReqauthAction
    setabi: SysioBiosSetabiAction
    setalimits: SysioBiosSetalimitsAction
    setcode: SysioBiosSetcodeAction
    setfinalizer: SysioBiosSetfinalizerAction
    setparams: SysioBiosSetparamsAction
    setpriv: SysioBiosSetprivAction
    setprodkeys: SysioBiosSetprodkeysAction
    setprods: SysioBiosSetprodsAction
    unlinkauth: SysioBiosUnlinkauthAction
    updateauth: SysioBiosUpdateauthAction
  }
  tables: {
    abihash: SysioBiosAbiHashType
  }
}

// ── sysio.chains ──

/** sysio.chains::ChainKind (enum, int32) */
export enum SysioChainsChainkind {
  CHAIN_KIND_UNKNOWN = 0,
  CHAIN_KIND_WIRE = 1,
  CHAIN_KIND_EVM = 2,
  CHAIN_KIND_SVM = 3,
}

/** sysio.chains::activchain (action) */
export interface SysioChainsActivchainAction {
  code: SysioChainsSlugNameType
}

/** sysio.chains::chain_key (type) */
export interface SysioChainsChainKeyType {
  code: SysioChainsSlugNameType
}

/** sysio.chains::chain_row (type) */
export interface SysioChainsChainRowType {
  code: SysioChainsSlugNameType
  kind: SysioChainsChainkind | keyof typeof SysioChainsChainkind
  external_chain_id: number
  name: string
  description: string
  is_depot: boolean
  active: boolean
  registered_at_ms: number | string
  activated_at_ms: number | string
}

/** sysio.chains::regchain (action) */
export interface SysioChainsRegchainAction {
  kind: SysioChainsChainkind | keyof typeof SysioChainsChainkind
  code: SysioChainsSlugNameType
  external_chain_id: number
  name: string
  description: string
}

/** sysio.chains::slug_name (type) */
export interface SysioChainsSlugNameType {
  value: number | string
}

/** sysio.chains - action + table surface for the typed contract client. */
export interface SysioChainsContract {
  actions: {
    activchain: SysioChainsActivchainAction
    regchain: SysioChainsRegchainAction
  }
  tables: {
    chains: SysioChainsChainRowType
  }
}

// ── sysio.chalg ──

/** sysio.chalg::DisputeStatus (enum, int32) */
export enum SysioChalgDisputestatus {
  DISPUTE_STATUS_UNKNOWN = 0,
  DISPUTE_STATUS_OPEN = 1,
  DISPUTE_STATUS_RESOLVED = 2,
}

/** sysio.chalg::chkdispute (action) */
export interface SysioChalgChkdisputeAction {
  dispute_id: number | string
}

/** sysio.chalg::dispute_candidate (type) */
export interface SysioChalgDisputeCandidateType {
  checksum: string
  operators: string[]
}

/** sysio.chalg::dispute_entry (type) */
export interface SysioChalgDisputeEntryType {
  id: number | string
  chain_code: number | string
  epoch_index: number
  status: SysioChalgDisputestatus | keyof typeof SysioChalgDisputestatus
  winning_checksum: string
  opened_at: string
  deadline: string
  candidates: SysioChalgDisputeCandidateType[]
}

/** sysio.chalg::dispute_key (type) */
export interface SysioChalgDisputeKeyType {
  id: number | string
}

/** sysio.chalg::dispute_vote (type) */
export interface SysioChalgDisputeVoteType {
  owner: string
  chosen_checksum: string
  voted_at: string
}

/** sysio.chalg::dispute_vote_key (type) */
export interface SysioChalgDisputeVoteKeyType {
  owner: number | string
}

/** sysio.chalg::opendispute (action) */
export interface SysioChalgOpendisputeAction {
  chain_code: number | string
  epoch_index: number
  candidates: SysioChalgDisputeCandidateType[]
}

/** sysio.chalg::slashop (action) */
export interface SysioChalgSlashopAction {
  operator_acct: string
  reason: string
}

/** sysio.chalg::votedispute (action) */
export interface SysioChalgVotedisputeAction {
  owner: string
  dispute_id: number | string
  chosen_checksum: string
}

/** sysio.chalg - action + table surface for the typed contract client. */
export interface SysioChalgContract {
  actions: {
    chkdispute: SysioChalgChkdisputeAction
    opendispute: SysioChalgOpendisputeAction
    slashop: SysioChalgSlashopAction
    votedispute: SysioChalgVotedisputeAction
  }
  tables: {
    disputes: SysioChalgDisputeEntryType
    disputevote: SysioChalgDisputeVoteType
  }
}

// ── sysio.dclaim ──

/** sysio.dclaim::ChainKind (enum, int32) */
export enum SysioDclaimChainkind {
  CHAIN_KIND_UNKNOWN = 0,
  CHAIN_KIND_WIRE = 1,
  CHAIN_KIND_EVM = 2,
  CHAIN_KIND_SVM = 3,
}

/** sysio.dclaim::cap_config (type) */
export interface SysioDclaimCapConfigType {
  imported_complete: boolean
  claim_window_sec: number
}

/** sysio.dclaim::cap_counters (type) */
export interface SysioDclaimCapCountersType {
  next_unmapped_id: number | string
  next_cursor_id: number | string
}

/** sysio.dclaim::claim (action) */
export interface SysioDclaimClaimAction {
  wire_account: string
}

/** sysio.dclaim::flushexpired (action) */
export interface SysioDclaimFlushexpiredAction {
  max_rows: number
}

/** sysio.dclaim::import_credit (type) */
export interface SysioDclaimImportCreditType {
  native_address: string
  wire_atomic: number | string
}

/** sysio.dclaim::importdone (action) */
export interface SysioDclaimImportdoneAction {
}

/** sysio.dclaim::importseed (action) */
export interface SysioDclaimImportseedAction {
  chain: SysioDclaimChainkind | keyof typeof SysioDclaimChainkind
  credits: SysioDclaimImportCreditType[]
}

/** sysio.dclaim::linkswept (action) */
export interface SysioDclaimLinksweptAction {
  wire_account: string
  chain: SysioDclaimChainkind | keyof typeof SysioDclaimChainkind
  native_pubkey: string
}

/** sysio.dclaim::onreward (action) */
export interface SysioDclaimOnrewardAction {
  chain_code: number | string
  staker_wire_account: string
  reward_chain: SysioDclaimChainkind | keyof typeof SysioDclaimChainkind
  staker_native_addr: string
  reward_amount: number | string
  reward_epoch_index: number
  external_epoch_ref: number | string
  share_bps: number
}

/** sysio.dclaim::pclaim_key (type) */
export interface SysioDclaimPclaimKeyType {
  wire_account: number | string
}

/** sysio.dclaim::pending_claim (type) */
export interface SysioDclaimPendingClaimType {
  wire_account: string
  balance: string
  expires_at_sec: number
}

/** sysio.dclaim::reward_cursor (type) */
export interface SysioDclaimRewardCursorType {
  id: number | string
  chain_code: number | string
  chain: SysioDclaimChainkind | keyof typeof SysioDclaimChainkind
  native_pubkey: string
  last_external_epoch_ref: number | string
}

/** sysio.dclaim::rwdcur_key (type) */
export interface SysioDclaimRwdcurKeyType {
  id: number | string
}

/** sysio.dclaim::setclmwindow (action) */
export interface SysioDclaimSetclmwindowAction {
  window_sec: number
}

/** sysio.dclaim::setconfig (action) */
export interface SysioDclaimSetconfigAction {
}

/** sysio.dclaim::unmapped_key (type) */
export interface SysioDclaimUnmappedKeyType {
  id: number | string
}

/** sysio.dclaim::unmapped_token (type) */
export interface SysioDclaimUnmappedTokenType {
  id: number | string
  chain_kind: SysioDclaimChainkind | keyof typeof SysioDclaimChainkind
  native_pubkey: string
  balance: string
  expires_at_sec: number
}

/** sysio.dclaim - action + table surface for the typed contract client. */
export interface SysioDclaimContract {
  actions: {
    claim: SysioDclaimClaimAction
    flushexpired: SysioDclaimFlushexpiredAction
    importdone: SysioDclaimImportdoneAction
    importseed: SysioDclaimImportseedAction
    linkswept: SysioDclaimLinksweptAction
    onreward: SysioDclaimOnrewardAction
    setclmwindow: SysioDclaimSetclmwindowAction
    setconfig: SysioDclaimSetconfigAction
  }
  tables: {
    capcfg: SysioDclaimCapConfigType
    capcounters: SysioDclaimCapCountersType
    pclaims: SysioDclaimPendingClaimType
    rwdcursors: SysioDclaimRewardCursorType
    unmapped: SysioDclaimUnmappedTokenType
  }
}

// ── sysio.epoch ──

/** sysio.epoch::EmissionsBlockReason (enum, int32) */
export enum SysioEpochEmissionsblockreason {
  EMISSIONS_BLOCK_REASON_UNSPECIFIED = 0,
  EMISSIONS_BLOCK_REASON_CONFIG_MISSING = 1,
  EMISSIONS_BLOCK_REASON_STATE_UNINITIALIZED = 2,
  EMISSIONS_BLOCK_REASON_TREASURY_EXHAUSTED = 3,
  EMISSIONS_BLOCK_REASON_BALANCE_INSUFFICIENT = 4,
}

/** sysio.epoch::advance (action) */
export interface SysioEpochAdvanceAction {
}

/** sysio.epoch::blocklog_entry (type) */
export interface SysioEpochBlocklogEntryType {
  epoch_index: number
  reason: SysioEpochEmissionsblockreason | keyof typeof SysioEpochEmissionsblockreason
  attempted_emission: number | string
  treasury_remaining: number | string
  sysio_balance: number | string
  first_blocked_at: number
  last_retry_at: number
  retry_count: number
}

/** sysio.epoch::blocklog_key (type) */
export interface SysioEpochBlocklogKeyType {
  epoch_index: number | string
}

/** sysio.epoch::epoch_config (type) */
export interface SysioEpochEpochConfigType {
  epoch_duration_sec: number
  operators_per_epoch: number
  batch_operator_minimum_active: number
  batch_op_groups: number
  epoch_retention_envelope_log_count: number
}

/** sysio.epoch::epoch_state (type) */
export interface SysioEpochEpochStateType {
  current_epoch_index: number
  current_epoch_start: string
  next_epoch_start: string
  current_batch_op_group: number
  batch_op_groups: string[][]
  last_consensus_hash: string
  is_paused: boolean
}

/** sysio.epoch::pause (action) */
export interface SysioEpochPauseAction {
}

/** sysio.epoch::schbatchgps (action) */
export interface SysioEpochSchbatchgpsAction {
}

/** sysio.epoch::setconfig (action) */
export interface SysioEpochSetconfigAction {
  epoch_duration_sec: number
  operators_per_epoch: number
  batch_operator_minimum_active: number
  batch_op_groups: number
  epoch_retention_envelope_log_count: number
}

/** sysio.epoch::unpause (action) */
export interface SysioEpochUnpauseAction {
}

/** sysio.epoch - action + table surface for the typed contract client. */
export interface SysioEpochContract {
  actions: {
    advance: SysioEpochAdvanceAction
    pause: SysioEpochPauseAction
    schbatchgps: SysioEpochSchbatchgpsAction
    setconfig: SysioEpochSetconfigAction
    unpause: SysioEpochUnpauseAction
  }
  tables: {
    blocklog: SysioEpochBlocklogEntryType
    epochcfg: SysioEpochEpochConfigType
    epochstate: SysioEpochEpochStateType
  }
}

// ── sysio.msgch ──

/** sysio.msgch::AttestationStatus (enum, int32) */
export enum SysioMsgchAttestationstatus {
  ATTESTATION_STATUS_PENDING = 0,
  ATTESTATION_STATUS_READY = 1,
  ATTESTATION_STATUS_PROCESSED = 2,
}

/** sysio.msgch::AttestationType (enum, int32) */
export enum SysioMsgchAttestationtype {
  ATTESTATION_TYPE_UNSPECIFIED = 0,
  ATTESTATION_TYPE_OPERATOR_ACTION = 2001,
  ATTESTATION_TYPE_STAKE = 3001,
  ATTESTATION_TYPE_UNSTAKE = 3002,
  ATTESTATION_TYPE_PRETOKEN_PURCHASE = 3004,
  ATTESTATION_TYPE_PRETOKEN_YIELD = 3006,
  ATTESTATION_TYPE_RESERVE_BALANCE_SHEET = 43520,
  ATTESTATION_TYPE_STAKE_UPDATE = 60928,
  ATTESTATION_TYPE_WIRE_TOKEN_PURCHASE = 60930,
  ATTESTATION_TYPE_CHALLENGE_RESPONSE = 60932,
  ATTESTATION_TYPE_SWAP_REQUEST = 60934,
  ATTESTATION_TYPE_SWAP_REMIT = 60944,
  ATTESTATION_TYPE_CHALLENGE_REQUEST = 60945,
  ATTESTATION_TYPE_OPERATORS = 60947,
  ATTESTATION_TYPE_BATCH_OPERATOR_GROUPS = 60943,
  ATTESTATION_TYPE_NODE_OWNER_REG = 60949,
  ATTESTATION_TYPE_STAKING_REWARD = 60950,
  ATTESTATION_TYPE_STAKE_RESULT = 60951,
  ATTESTATION_TYPE_ATTESTATION_PROCESSING_ERROR = 60952,
  ATTESTATION_TYPE_UNDERWRITE_INTENT_COMMIT = 60953,
  ATTESTATION_TYPE_SWAP_REVERT = 60955,
  ATTESTATION_TYPE_DEPOSIT_REVERT = 60956,
  ATTESTATION_TYPE_RESERVE_CREATE = 60958,
  ATTESTATION_TYPE_RESERVE_CREATE_CANCEL = 60959,
  ATTESTATION_TYPE_RESERVE_CREATE_CANCELLED = 60960,
  ATTESTATION_TYPE_RESERVE_READY = 60961,
  ATTESTATION_TYPE_EMISSIONS_BLOCKED = 60962,
}

/** sysio.msgch::ChainKind (enum, int32) */
export enum SysioMsgchChainkind {
  CHAIN_KIND_UNKNOWN = 0,
  CHAIN_KIND_WIRE = 1,
  CHAIN_KIND_EVM = 2,
  CHAIN_KIND_SVM = 3,
}

/** sysio.msgch::EnvelopeStatus (enum, int32) */
export enum SysioMsgchEnvelopestatus {
  ENVELOPE_STATUS_PENDING_DELIVERY = 0,
  ENVELOPE_STATUS_DELIVERED = 1,
  ENVELOPE_STATUS_CONFIRMED = 2,
}

/** sysio.msgch::MessageDirection (enum, int32) */
export enum SysioMsgchMessagedirection {
  MESSAGE_DIRECTION_INBOUND = 0,
  MESSAGE_DIRECTION_OUTBOUND = 1,
}

/** sysio.msgch::MessageStatus (enum, int32) */
export enum SysioMsgchMessagestatus {
  MESSAGE_STATUS_PENDING = 0,
  MESSAGE_STATUS_READY = 1,
  MESSAGE_STATUS_PROCESSED = 2,
  MESSAGE_STATUS_CANCELLED = 3,
}

/** sysio.msgch::ChainId (type) */
export interface SysioMsgchChainidType {
  kind: SysioMsgchChainkind | keyof typeof SysioMsgchChainkind
  id: SysioMsgchVarintUint32Type
}

/** sysio.msgch::Endpoints (type) */
export interface SysioMsgchEndpointsType {
  start: SysioMsgchChainidType
  end: SysioMsgchChainidType
}

/** sysio.msgch::att_seq_entry (type) */
export interface SysioMsgchAttSeqEntryType {
  id: number | string
  next: number | string
}

/** sysio.msgch::att_seq_key (type) */
export interface SysioMsgchAttSeqKeyType {
  id: number | string
}

/** sysio.msgch::attestation_entry (type) */
export interface SysioMsgchAttestationEntryType {
  id: number | string
  chain_code: number | string
  epoch_index: number
  type: SysioMsgchAttestationtype | keyof typeof SysioMsgchAttestationtype
  status: SysioMsgchAttestationstatus | keyof typeof SysioMsgchAttestationstatus
  data: string
  pending_timestamp: number | string
  ready_timestamp: number | string
  processed_timestamp: number | string
}

/** sysio.msgch::bootstrap (action) */
export interface SysioMsgchBootstrapAction {
}

/** sysio.msgch::buildenv (action) */
export interface SysioMsgchBuildenvAction {
  chain_code: number | string
}

/** sysio.msgch::chkcons (action) */
export interface SysioMsgchChkconsAction {
}

/** sysio.msgch::deliver (action) */
export interface SysioMsgchDeliverAction {
  batch_op_name: string
  chain_code: number | string
  data: string
}

/** sysio.msgch::envelope_entry (type) */
export interface SysioMsgchEnvelopeEntryType {
  id: number | string
  chain_code: number | string
  epoch_index: number
  batch_op_name: string
  chain_kind: SysioMsgchChainkind | keyof typeof SysioMsgchChainkind
  checksum: string
  raw_data: string
  received_at: string
}

/** sysio.msgch::envelope_log_entry (type) */
export interface SysioMsgchEnvelopeLogEntryType {
  id: number | string
  endpoints: SysioMsgchEndpointsType
  epoch_index: number
  checksum: string
  emitted_at: string
}

/** sysio.msgch::evalcons (action) */
export interface SysioMsgchEvalconsAction {
  chain_code: number | string
  epoch_index: number
}

/** sysio.msgch::id_key (type) */
export interface SysioMsgchIdKeyType {
  id: number | string
}

/** sysio.msgch::message_entry (type) */
export interface SysioMsgchMessageEntryType {
  id: number | string
  chain_code: number | string
  epoch_index: number
  message_id: string
  previous_message_id: string
  direction: SysioMsgchMessagedirection | keyof typeof SysioMsgchMessagedirection
  status: SysioMsgchMessagestatus | keyof typeof SysioMsgchMessagestatus
  raw_payload: string
  received_at: string
  processed_at: string
}

/** sysio.msgch::outbound_envelope (type) */
export interface SysioMsgchOutboundEnvelopeType {
  id: number | string
  chain_code: number | string
  epoch_index: number
  envelope_hash: string
  status: SysioMsgchEnvelopestatus | keyof typeof SysioMsgchEnvelopestatus
  raw_envelope: string
}

/** sysio.msgch::outpost_consensus_entry (type) */
export interface SysioMsgchOutpostConsensusEntryType {
  chain_code: number | string
  epoch_index: number
  consensus_reached: boolean
  winning_checksum: string
  envelope_digest: string
}

/** sysio.msgch::outpost_consensus_key (type) */
export interface SysioMsgchOutpostConsensusKeyType {
  chain_code: number | string
}

/** sysio.msgch::queueout (action) */
export interface SysioMsgchQueueoutAction {
  chain_code: number | string
  attest_type: SysioMsgchAttestationtype | keyof typeof SysioMsgchAttestationtype
  data: string
}

/** sysio.msgch::resolvedisp (action) */
export interface SysioMsgchResolvedispAction {
  chain_code: number | string
  epoch_index: number
  winning_checksum: string
}

/** sysio.msgch::varint_uint32 (type) */
export interface SysioMsgchVarintUint32Type {
  value: number
}

/** sysio.msgch - action + table surface for the typed contract client. */
export interface SysioMsgchContract {
  actions: {
    bootstrap: SysioMsgchBootstrapAction
    buildenv: SysioMsgchBuildenvAction
    chkcons: SysioMsgchChkconsAction
    deliver: SysioMsgchDeliverAction
    evalcons: SysioMsgchEvalconsAction
    queueout: SysioMsgchQueueoutAction
    resolvedisp: SysioMsgchResolvedispAction
  }
  tables: {
    attestations: SysioMsgchAttestationEntryType
    attseq: SysioMsgchAttSeqEntryType
    envelopes: SysioMsgchEnvelopeEntryType
    envlog: SysioMsgchEnvelopeLogEntryType
    messages: SysioMsgchMessageEntryType
    outenvelopes: SysioMsgchOutboundEnvelopeType
    outpcons: SysioMsgchOutpostConsensusEntryType
  }
}

// ── sysio.msig ──

/** sysio.msig::action (type) */
export interface SysioMsigActionType {
  account: string
  name: string
  authorization: SysioMsigPermissionLevelType[]
  data: string
}

/** sysio.msig::approval (type) */
export interface SysioMsigApprovalType {
  level: SysioMsigPermissionLevelType
  time: string
}

/** sysio.msig::approval_key (type) */
export interface SysioMsigApprovalKeyType {
  proposal_name: number | string
}

/** sysio.msig::approvals_info (type) */
export interface SysioMsigApprovalsInfoType {
  version: number
  proposal_name: string
  requested_approvals: SysioMsigApprovalType[]
  provided_approvals: SysioMsigApprovalType[]
}

/** sysio.msig::approve (action) */
export interface SysioMsigApproveAction {
  proposer: string
  proposal_name: string
  level: SysioMsigPermissionLevelType
  proposal_hash: unknown
}

/** sysio.msig::cancel (action) */
export interface SysioMsigCancelAction {
  proposer: string
  proposal_name: string
  canceler: string
}

/** sysio.msig::exec (action) */
export interface SysioMsigExecAction {
  proposer: string
  proposal_name: string
  executer: string
}

/** sysio.msig::extension (type) */
export interface SysioMsigExtensionType {
  type: number
  data: string
}

/** sysio.msig::getproposal (action) */
export interface SysioMsigGetproposalAction {
  proposer: string
  proposal_name: string
}

/** sysio.msig::inval_key (type) */
export interface SysioMsigInvalKeyType {
  account: number | string
}

/** sysio.msig::invalidate (action) */
export interface SysioMsigInvalidateAction {
  account: string
}

/** sysio.msig::invalidation (type) */
export interface SysioMsigInvalidationType {
  account: string
  last_invalidation_time: string
}

/** sysio.msig::old_approval_key (type) */
export interface SysioMsigOldApprovalKeyType {
  proposal_name: number | string
}

/** sysio.msig::old_approvals_info (type) */
export interface SysioMsigOldApprovalsInfoType {
  proposal_name: string
  requested_approvals: SysioMsigPermissionLevelType[]
  provided_approvals: SysioMsigPermissionLevelType[]
}

/** sysio.msig::permission_level (type) */
export interface SysioMsigPermissionLevelType {
  actor: string
  permission: string
}

/** sysio.msig::propchunk (type) */
export interface SysioMsigPropchunkType {
  proposal_name: string
  chunk_index: number
  data: string
}

/** sysio.msig::propchunk_key (type) */
export interface SysioMsigPropchunkKeyType {
  proposal_name: number | string
  chunk_index: number
}

/** sysio.msig::proposal (type) */
export interface SysioMsigProposalType {
  proposal_name: string
  packed_transaction: string
  earliest_exec_time: unknown
  chunk_count: unknown
  total_size: unknown
  trx_hash: unknown
}

/** sysio.msig::proposal_key (type) */
export interface SysioMsigProposalKeyType {
  proposal_name: number | string
}

/** sysio.msig::propose (action) */
export interface SysioMsigProposeAction {
  proposer: string
  proposal_name: string
  requested: SysioMsigPermissionLevelType[]
  trx: SysioMsigTransactionType
}

/** sysio.msig::transaction (type) */
export interface SysioMsigTransactionType {
  context_free_actions: SysioMsigActionType[]
  actions: SysioMsigActionType[]
  transaction_extensions: SysioMsigExtensionType[]
}

/** sysio.msig::transaction_header (type) */
export interface SysioMsigTransactionHeaderType {
  expiration: string
  ref_block_num: number
  ref_block_prefix: number
  max_net_usage_words: number
  max_cpu_usage_ms: number
  delay_sec: number
}

/** sysio.msig::unapprove (action) */
export interface SysioMsigUnapproveAction {
  proposer: string
  proposal_name: string
  level: SysioMsigPermissionLevelType
}

/** sysio.msig - action + table surface for the typed contract client. */
export interface SysioMsigContract {
  actions: {
    approve: SysioMsigApproveAction
    cancel: SysioMsigCancelAction
    exec: SysioMsigExecAction
    getproposal: SysioMsigGetproposalAction
    invalidate: SysioMsigInvalidateAction
    propose: SysioMsigProposeAction
    unapprove: SysioMsigUnapproveAction
  }
  tables: {
    approvals: SysioMsigOldApprovalsInfoType
    approvals2: SysioMsigApprovalsInfoType
    invals: SysioMsigInvalidationType
    propchunks: SysioMsigPropchunkType
    proposal: SysioMsigProposalType
  }
}

// ── sysio.opreg ──

/** sysio.opreg::ActionType (enum, int32) */
export enum SysioOpregActiontype {
  ACTION_TYPE_UNKNOWN = 0,
  ACTION_TYPE_DEPOSIT_REQUEST = 1,
  ACTION_TYPE_WITHDRAW_REQUEST = 2,
  ACTION_TYPE_WITHDRAW_REMIT = 3,
  ACTION_TYPE_SLASH = 4,
}

/** sysio.opreg::ChainKind (enum, int32) */
export enum SysioOpregChainkind {
  CHAIN_KIND_UNKNOWN = 0,
  CHAIN_KIND_WIRE = 1,
  CHAIN_KIND_EVM = 2,
  CHAIN_KIND_SVM = 3,
}

/** sysio.opreg::OperatorStatus (enum, int32) */
export enum SysioOpregOperatorstatus {
  OPERATOR_STATUS_UNKNOWN = 0,
  OPERATOR_STATUS_WARMUP = 1,
  OPERATOR_STATUS_COOLDOWN = 2,
  OPERATOR_STATUS_ACTIVE = 3,
  OPERATOR_STATUS_TERMINATED = 240,
  OPERATOR_STATUS_SLASHED = 241,
}

/** sysio.opreg::OperatorType (enum, int32) */
export enum SysioOpregOperatortype {
  OPERATOR_TYPE_UNKNOWN = 0,
  OPERATOR_TYPE_PRODUCER = 1,
  OPERATOR_TYPE_BATCH = 2,
  OPERATOR_TYPE_UNDERWRITER = 3,
  OPERATOR_TYPE_CHALLENGER = 4,
}

/** sysio.opreg::ChainAddress (type) */
export interface SysioOpregChainaddressType {
  kind: SysioOpregChainkind | keyof typeof SysioOpregChainkind
  address: string
}

/** sysio.opreg::OperatorAction (type) */
export interface SysioOpregOperatoractionType {
  action_type: SysioOpregActiontype | keyof typeof SysioOpregActiontype
  op_address: SysioOpregChainaddressType
  type: SysioOpregOperatortype | keyof typeof SysioOpregOperatortype
  status: SysioOpregOperatorstatus | keyof typeof SysioOpregOperatorstatus
  amount: SysioOpregTokenamountType
  request_id: SysioOpregVarintUint64Type
  chain_code: SysioOpregVarintUint64Type
  reason: string
  reserve_code: SysioOpregVarintUint64Type
}

/** sysio.opreg::OperatorActionLog (type) */
export interface SysioOpregOperatoractionlogType {
  action: SysioOpregOperatoractionType
  success: boolean
  timestamp: SysioOpregVarintInt64Type
  error_message: string
}

/** sysio.opreg::TokenAmount (type) */
export interface SysioOpregTokenamountType {
  token_code: SysioOpregVarintUint64Type
  amount: SysioOpregVarintInt64Type
}

/** sysio.opreg::available (action) */
export interface SysioOpregAvailableAction {
  account: string
  chain_code: SysioOpregSlugNameType
  token_code: SysioOpregSlugNameType
}

/** sysio.opreg::balance_entry (type) */
export interface SysioOpregBalanceEntryType {
  chain_code: SysioOpregSlugNameType
  token_code: SysioOpregSlugNameType
  balance: number | string
  last_updated_ms: number | string
}

/** sysio.opreg::cancelwtdw (action) */
export interface SysioOpregCancelwtdwAction {
  account: string
  request_id: number | string
}

/** sysio.opreg::chain_min_bond (type) */
export interface SysioOpregChainMinBondType {
  chain_code: SysioOpregSlugNameType
  token_code: SysioOpregSlugNameType
  min_bond: number | string
  config_timestamp_ms: number | string
}

/** sysio.opreg::delivery_key (type) */
export interface SysioOpregDeliveryKeyType {
  log_id: number | string
}

/** sysio.opreg::delivery_log_entry (type) */
export interface SysioOpregDeliveryLogEntryType {
  log_id: number | string
  account: string
  epoch: number
  delivered: boolean
  ts_ms: number | string
}

/** sysio.opreg::deposit (action) */
export interface SysioOpregDepositAction {
  account: string
  amount: number | string
}

/** sysio.opreg::depositinle (action) */
export interface SysioOpregDepositinleAction {
  account: string
  chain_code: SysioOpregSlugNameType
  token_code: SysioOpregSlugNameType
  amount: number | string
  actor_chain: SysioOpregChainkind | keyof typeof SysioOpregChainkind
  actor_address: string
  original_message_id: string
}

/** sysio.opreg::flushwtdw (action) */
export interface SysioOpregFlushwtdwAction {
  current_epoch: number
}

/** sysio.opreg::op_config (type) */
export interface SysioOpregOpConfigType {
  req_prod_collat: SysioOpregChainMinBondType[]
  req_batchop_collat: SysioOpregChainMinBondType[]
  req_uw_collat: SysioOpregChainMinBondType[]
  max_available_producers: number
  max_available_batch_ops: number
  max_available_underwriters: number
  terminate_prune_delay_ms: number | string
  terminate_max_consecutive_misses: number
  terminate_max_pct_misses_24h: number
  terminate_window_ms: number | string
}

/** sysio.opreg::op_counters (type) */
export interface SysioOpregOpCountersType {
  next_withdraw_id: number | string
  next_dellog_id: number | string
}

/** sysio.opreg::operator_entry (type) */
export interface SysioOpregOperatorEntryType {
  account: string
  type: SysioOpregOperatortype | keyof typeof SysioOpregOperatortype
  status: SysioOpregOperatorstatus | keyof typeof SysioOpregOperatorstatus
  is_bootstrapped: boolean
  balances: SysioOpregBalanceEntryType[]
  registered_at: number | string
  available_at: number | string
  updated_at: number | string
  terminated_at: number | string
  status_reason: string
  recent_actions: SysioOpregOperatoractionlogType[]
}

/** sysio.opreg::operator_key (type) */
export interface SysioOpregOperatorKeyType {
  account: number | string
}

/** sysio.opreg::processbatch (action) */
export interface SysioOpregProcessbatchAction {
  account: string
  was_eligible: boolean
  is_eligible: boolean
}

/** sysio.opreg::processprod (action) */
export interface SysioOpregProcessprodAction {
  account: string
  was_eligible: boolean
  is_eligible: boolean
}

/** sysio.opreg::processuw (action) */
export interface SysioOpregProcessuwAction {
  account: string
  was_eligible: boolean
  is_eligible: boolean
}

/** sysio.opreg::prune (action) */
export interface SysioOpregPruneAction {
}

/** sysio.opreg::recorddel (action) */
export interface SysioOpregRecorddelAction {
  account: string
  epoch: number
  delivered: boolean
}

/** sysio.opreg::regoperator (action) */
export interface SysioOpregRegoperatorAction {
  account: string
  type: SysioOpregOperatortype | keyof typeof SysioOpregOperatortype
  is_bootstrapped: boolean
}

/** sysio.opreg::releaselock (action) */
export interface SysioOpregReleaselockAction {
  account: string
  chain_code: SysioOpregSlugNameType
  token_code: SysioOpregSlugNameType
  amount: number | string
}

/** sysio.opreg::setconfig (action) */
export interface SysioOpregSetconfigAction {
  max_available_producers: number
  max_available_batch_ops: number
  max_available_underwriters: number
  terminate_prune_delay_ms: number | string
  terminate_max_consecutive_misses: number
  terminate_max_pct_misses_24h: number
  terminate_window_ms: number | string
  req_prod_collat: SysioOpregChainMinBondType[]
  req_batchop_collat: SysioOpregChainMinBondType[]
  req_uw_collat: SysioOpregChainMinBondType[]
}

/** sysio.opreg::slash (action) */
export interface SysioOpregSlashAction {
  account: string
  reason: string
}

/** sysio.opreg::slug_name (type) */
export interface SysioOpregSlugNameType {
  value: number | string
}

/** sysio.opreg::termcheck (action) */
export interface SysioOpregTermcheckAction {
  account: string
}

/** sysio.opreg::terminate (action) */
export interface SysioOpregTerminateAction {
  account: string
  reason: string
}

/** sysio.opreg::varint_int64 (type) */
export interface SysioOpregVarintInt64Type {
  value: number | string
}

/** sysio.opreg::varint_uint64 (type) */
export interface SysioOpregVarintUint64Type {
  value: number | string
}

/** sysio.opreg::withdraw (action) */
export interface SysioOpregWithdrawAction {
  account: string
  amount: number | string
}

/** sysio.opreg::withdraw_key (type) */
export interface SysioOpregWithdrawKeyType {
  request_id: number | string
}

/** sysio.opreg::withdraw_request (type) */
export interface SysioOpregWithdrawRequestType {
  request_id: number | string
  account: string
  chain_code: SysioOpregSlugNameType
  token_code: SysioOpregSlugNameType
  amount: number | string
  eligible_at_epoch: number
  requested_at_epoch: number
}

/** sysio.opreg::withdrawinle (action) */
export interface SysioOpregWithdrawinleAction {
  account: string
  chain_code: SysioOpregSlugNameType
  token_code: SysioOpregSlugNameType
  amount: number | string
}

/** sysio.opreg - action + table surface for the typed contract client. */
export interface SysioOpregContract {
  actions: {
    available: SysioOpregAvailableAction
    cancelwtdw: SysioOpregCancelwtdwAction
    deposit: SysioOpregDepositAction
    depositinle: SysioOpregDepositinleAction
    flushwtdw: SysioOpregFlushwtdwAction
    processbatch: SysioOpregProcessbatchAction
    processprod: SysioOpregProcessprodAction
    processuw: SysioOpregProcessuwAction
    prune: SysioOpregPruneAction
    recorddel: SysioOpregRecorddelAction
    regoperator: SysioOpregRegoperatorAction
    releaselock: SysioOpregReleaselockAction
    setconfig: SysioOpregSetconfigAction
    slash: SysioOpregSlashAction
    termcheck: SysioOpregTermcheckAction
    terminate: SysioOpregTerminateAction
    withdraw: SysioOpregWithdrawAction
    withdrawinle: SysioOpregWithdrawinleAction
  }
  tables: {
    dellog: SysioOpregDeliveryLogEntryType
    opconfig: SysioOpregOpConfigType
    opcounters: SysioOpregOpCountersType
    operators: SysioOpregOperatorEntryType
    wtdwqueue: SysioOpregWithdrawRequestType
  }
}

// ── sysio.reserv ──

/** sysio.reserv::ChainKind (enum, int32) */
export enum SysioReservChainkind {
  CHAIN_KIND_UNKNOWN = 0,
  CHAIN_KIND_WIRE = 1,
  CHAIN_KIND_EVM = 2,
  CHAIN_KIND_SVM = 3,
}

/** sysio.reserv::ReserveStatus (enum, int32) */
export enum SysioReservReservestatus {
  RESERVE_STATUS_UNKNOWN = 0,
  RESERVE_STATUS_PENDING = 1,
  RESERVE_STATUS_ACTIVE = 2,
  RESERVE_STATUS_CANCELLED = 3,
}

/** sysio.reserv::ChainAddress (type) */
export interface SysioReservChainaddressType {
  kind: SysioReservChainkind | keyof typeof SysioReservChainkind
  address: string
}

/** sysio.reserv::applyfromwire (action) */
export interface SysioReservApplyfromwireAction {
  dst_chain_code: SysioReservSlugNameType
  dst_token_code: SysioReservSlugNameType
  dst_reserve_code: SysioReservSlugNameType
  wire_in: number | string
  dst_amount: number | string
}

/** sysio.reserv::applyswap (action) */
export interface SysioReservApplyswapAction {
  src_chain_code: SysioReservSlugNameType
  src_token_code: SysioReservSlugNameType
  src_reserve_code: SysioReservSlugNameType
  src_amount: number | string
  dst_chain_code: SysioReservSlugNameType
  dst_token_code: SysioReservSlugNameType
  dst_reserve_code: SysioReservSlugNameType
  dst_amount: number | string
}

/** sysio.reserv::debit (action) */
export interface SysioReservDebitAction {
  chain_code: SysioReservSlugNameType
  token_code: SysioReservSlugNameType
  reserve_code: SysioReservSlugNameType
  amount: number | string
}

/** sysio.reserv::drainrewards (action) */
export interface SysioReservDrainrewardsAction {
  amount: number | string
}

/** sysio.reserv::matchreserve (action) */
export interface SysioReservMatchreserveAction {
  chain_code: SysioReservSlugNameType
  token_code: SysioReservSlugNameType
  reserve_code: SysioReservSlugNameType
  matcher: string
  wire_amount: number | string
}

/** sysio.reserv::oncnclrsv (action) */
export interface SysioReservOncnclrsvAction {
  chain_code: SysioReservSlugNameType
  token_code: SysioReservSlugNameType
  reserve_code: SysioReservSlugNameType
  creator_chain_kind: SysioReservChainkind | keyof typeof SysioReservChainkind
  creator_chain_addr: string
}

/** sysio.reserv::oncrtreserve (action) */
export interface SysioReservOncrtreserveAction {
  chain_code: SysioReservSlugNameType
  token_code: SysioReservSlugNameType
  reserve_code: SysioReservSlugNameType
  name: string
  description: string
  external_token_amount: number | string
  requested_wire_amount: number | string
  source_token_precision: number
  connector_weight_bps: number
  creator_chain_kind: SysioReservChainkind | keyof typeof SysioReservChainkind
  creator_chain_addr: string
  is_private: boolean
  creator_pub_key: string
}

/** sysio.reserv::paywire (action) */
export interface SysioReservPaywireAction {
  src_chain_code: SysioReservSlugNameType
  src_token_code: SysioReservSlugNameType
  src_reserve_code: SysioReservSlugNameType
  src_amount: number | string
  recipient: string
  wire_out: number | string
}

/** sysio.reserv::refundwire (action) */
export interface SysioReservRefundwireAction {
  recipient: string
  wire_amount: number | string
  revert_fee_bps: number
}

/** sysio.reserv::regreserve (action) */
export interface SysioReservRegreserveAction {
  chain_code: SysioReservSlugNameType
  token_code: SysioReservSlugNameType
  reserve_code: SysioReservSlugNameType
  name: string
  description: string
  initial_chain_amount: number | string
  initial_wire_amount: number | string
  source_token_precision: number
  connector_weight_bps: number
  is_private: boolean
  owner: string
}

/** sysio.reserv::reserve_key (type) */
export interface SysioReservReserveKeyType {
  chain_code: SysioReservSlugNameType
  token_code: SysioReservSlugNameType
  reserve_code: SysioReservSlugNameType
}

/** sysio.reserv::reserve_row (type) */
export interface SysioReservReserveRowType {
  chain_code: SysioReservSlugNameType
  token_code: SysioReservSlugNameType
  reserve_code: SysioReservSlugNameType
  name: string
  description: string
  status: SysioReservReservestatus | keyof typeof SysioReservReservestatus
  reserve_chain_amount: number | string
  reserve_wire_amount: number | string
  source_token_precision: number
  connector_weight_bps: number
  creator_addr: SysioReservChainaddressType
  requested_wire_amount: number | string
  external_token_amount: number | string
  registered_at_ms: number | string
  activated_at_ms: number | string
  cancelled_at_ms: number | string
  is_private: boolean
  owner: string
  creator_pub_key: string
}

/** sysio.reserv::rewardbal (action) */
export interface SysioReservRewardbalAction {
}

/** sysio.reserv::rewards_bucket (type) */
export interface SysioReservRewardsBucketType {
  balance: number | string
  lifetime_accrued: number | string
}

/** sysio.reserv::slug_name (type) */
export interface SysioReservSlugNameType {
  value: number | string
}

/** sysio.reserv::swapquote (action) */
export interface SysioReservSwapquoteAction {
  from_chain_code: SysioReservSlugNameType
  from_token_code: SysioReservSlugNameType
  from_reserve_code: SysioReservSlugNameType
  from_amount: number | string
  to_chain_code: SysioReservSlugNameType
  to_token_code: SysioReservSlugNameType
  to_reserve_code: SysioReservSlugNameType
}

/** sysio.reserv - action + table surface for the typed contract client. */
export interface SysioReservContract {
  actions: {
    applyfromwire: SysioReservApplyfromwireAction
    applyswap: SysioReservApplyswapAction
    debit: SysioReservDebitAction
    drainrewards: SysioReservDrainrewardsAction
    matchreserve: SysioReservMatchreserveAction
    oncnclrsv: SysioReservOncnclrsvAction
    oncrtreserve: SysioReservOncrtreserveAction
    paywire: SysioReservPaywireAction
    refundwire: SysioReservRefundwireAction
    regreserve: SysioReservRegreserveAction
    rewardbal: SysioReservRewardbalAction
    swapquote: SysioReservSwapquoteAction
  }
  tables: {
    reserves: SysioReservReserveRowType
    rewardbkt: SysioReservRewardsBucketType
  }
}

// ── sysio.roa ──

/** sysio.roa::activateroa (action) */
export interface SysioRoaActivateroaAction {
  total_sys: string
  bytes_per_unit: number | string
}

/** sysio.roa::addpolicy (action) */
export interface SysioRoaAddpolicyAction {
  owner: string
  issuer: string
  net_weight: string
  cpu_weight: string
  ram_weight: string
  time_block: number
  network_gen: number
}

/** sysio.roa::expandpolicy (action) */
export interface SysioRoaExpandpolicyAction {
  owner: string
  issuer: string
  net_weight: string
  cpu_weight: string
  ram_weight: string
  network_gen: number
}

/** sysio.roa::extendpolicy (action) */
export interface SysioRoaExtendpolicyAction {
  owner: string
  issuer: string
  new_time_block: number
}

/** sysio.roa::forcereg (action) */
export interface SysioRoaForceregAction {
  owner: string
  tier: number
}

/** sysio.roa::giftram (action) */
export interface SysioRoaGiftramAction {
  account: string
  usage_before: number | string
}

/** sysio.roa::newnameduser (action) */
export interface SysioRoaNewnameduserAction {
  account: string
  pubkey: string
  tier: number
}

/** sysio.roa::newuser (action) */
export interface SysioRoaNewuserAction {
  creator: string
  nonce: string
  pubkey: string
}

/** sysio.roa::nodeowner_key (type) */
export interface SysioRoaNodeownerKeyType {
  owner: number | string
}

/** sysio.roa::nodeownerreg (type) */
export interface SysioRoaNodeownerregType {
  owner: string
  status: number
  tier: number
  reason: number
}

/** sysio.roa::nodeownerreg_key (type) */
export interface SysioRoaNodeownerregKeyType {
  owner: number | string
}

/** sysio.roa::nodeowners (type) */
export interface SysioRoaNodeownersType {
  owner: string
  tier: number
  total_sys: string
  allocated_sys: string
  allocated_bw: string
  allocated_ram: string
  network_gen: number
}

/** sysio.roa::nodeownreg (action) */
export interface SysioRoaNodeownregAction {
  owner: string
  tier: number
  eth_pub_key: string
  wire_pub_key: string
}

/** sysio.roa::policies (type) */
export interface SysioRoaPoliciesType {
  owner: string
  issuer: string
  net_weight: string
  cpu_weight: string
  ram_weight: string
  bytes_per_unit: number | string
  time_block: number
}

/** sysio.roa::policy_key (type) */
export interface SysioRoaPolicyKeyType {
  owner: number | string
}

/** sysio.roa::reducepolicy (action) */
export interface SysioRoaReducepolicyAction {
  owner: string
  issuer: string
  net_weight: string
  cpu_weight: string
  ram_weight: string
  network_gen: number
}

/** sysio.roa::reslimit (type) */
export interface SysioRoaReslimitType {
  owner: string
  net_weight: string
  cpu_weight: string
  ram_bytes: number | string
}

/** sysio.roa::reslimit_key (type) */
export interface SysioRoaReslimitKeyType {
  owner: number | string
}

/** sysio.roa::roa_state (type) */
export interface SysioRoaRoaStateType {
  is_active: boolean
  total_sys: string
  bytes_per_unit: number | string
  network_gen: number
}

/** sysio.roa::setbyteprice (action) */
export interface SysioRoaSetbytepriceAction {
  bytes_per_unit: number | string
}

/** sysio.roa::setsysabi (action) */
export interface SysioRoaSetsysabiAction {
  account: string
  abi: string
}

/** sysio.roa::setsyscode (action) */
export interface SysioRoaSetsyscodeAction {
  account: string
  vmtype: number
  vmversion: number
  code: string
}

/** sysio.roa::sponsor (type) */
export interface SysioRoaSponsorType {
  nonce: string
  username: string
}

/** sysio.roa::sponsor_key (type) */
export interface SysioRoaSponsorKeyType {
  nonce: number | string
}

/** sysio.roa::sponsorcount (type) */
export interface SysioRoaSponsorcountType {
  owner: string
  count: number | string
}

/** sysio.roa::sponsorcount_key (type) */
export interface SysioRoaSponsorcountKeyType {
  owner: number | string
}

/** sysio.roa - action + table surface for the typed contract client. */
export interface SysioRoaContract {
  actions: {
    activateroa: SysioRoaActivateroaAction
    addpolicy: SysioRoaAddpolicyAction
    expandpolicy: SysioRoaExpandpolicyAction
    extendpolicy: SysioRoaExtendpolicyAction
    forcereg: SysioRoaForceregAction
    giftram: SysioRoaGiftramAction
    newnameduser: SysioRoaNewnameduserAction
    newuser: SysioRoaNewuserAction
    nodeownreg: SysioRoaNodeownregAction
    reducepolicy: SysioRoaReducepolicyAction
    setbyteprice: SysioRoaSetbytepriceAction
    setsysabi: SysioRoaSetsysabiAction
    setsyscode: SysioRoaSetsyscodeAction
  }
  tables: {
    nodeownerreg: SysioRoaNodeownerregType
    nodeowners: SysioRoaNodeownersType
    policies: SysioRoaPoliciesType
    reslimit: SysioRoaReslimitType
    roastate: SysioRoaRoaStateType
    sponsorcount: SysioRoaSponsorcountType
    sponsors: SysioRoaSponsorType
  }
}

// ── sysio.system ──

/** sysio.system::trx_match_type (enum, uint8) */
export enum SysioSystemTrxMatchType {
  only = 0,
  first = 1,
  any = 2,
}

/** sysio.system::abi_hash (type) */
export interface SysioSystemAbiHashType {
  owner: string
  hash: string
}

/** sysio.system::abihash_key (type) */
export interface SysioSystemAbihashKeyType {
  owner: number | string
}

/** sysio.system::accrueepoch (action) */
export interface SysioSystemAccrueepochAction {
  epoch_index: number
  batch_group_index: number
  per_epoch_emission: number | string
}

/** sysio.system::actfinkey (action) */
export interface SysioSystemActfinkeyAction {
  finalizer_name: string
  finalizer_key: string
}

/** sysio.system::activate (action) */
export interface SysioSystemActivateAction {
  feature_digest: string
}

/** sysio.system::addnodeowner (action) */
export interface SysioSystemAddnodeownerAction {
  account_name: string
  tier: number
}

/** sysio.system::authority (type) */
export interface SysioSystemAuthorityType {
  threshold: number
  keys: SysioSystemKeyWeightType[]
  accounts: SysioSystemPermissionLevelWeightType[]
}

/** sysio.system::block_header (type) */
export interface SysioSystemBlockHeaderType {
  timestamp: number
  producer: string
  confirmed: number
  previous: string
  transaction_mroot: string
  action_mroot: string
  schedule_version: number
  new_producers?: SysioSystemProducerScheduleType | null
}

/** sysio.system::block_info_record (type) */
export interface SysioSystemBlockInfoRecordType {
  version: number
  block_height: number
  block_timestamp: string
}

/** sysio.system::block_signing_authority_v0 (type) */
export interface SysioSystemBlockSigningAuthorityV0Type {
  threshold: number
  keys: SysioSystemKeyWeightType[]
}

/** sysio.system::blockchain_parameters (type) */
export interface SysioSystemBlockchainParametersType {
  max_block_net_usage: number | string
  target_block_net_usage_pct: number
  max_transaction_net_usage: number
  net_usage_leeway: number
  context_free_discount_net_usage_num: number
  context_free_discount_net_usage_den: number
  max_block_cpu_usage: number
  target_block_cpu_usage_pct: number
  max_transaction_cpu_usage: number
  min_transaction_cpu_usage: number
  max_transaction_lifetime: number
  max_transaction_delay: number
  max_inline_action_size: number
  max_inline_action_depth: number
  max_authority_depth: number
  max_action_return_value_size: number
  max_kv_key_size: number
  max_kv_value_size: number
  max_kv_secondary_key_size: number
}

/** sysio.system::blockinfo_key (type) */
export interface SysioSystemBlockinfoKeyType {
  block_height: number | string
}

/** sysio.system::claimnodedis (action) */
export interface SysioSystemClaimnodedisAction {
  account_name: string
}

/** sysio.system::deleteauth (action) */
export interface SysioSystemDeleteauthAction {
  account: string
  permission: string
  authorized_by: unknown
}

/** sysio.system::delfinkey (action) */
export interface SysioSystemDelfinkeyAction {
  finalizer_name: string
  finalizer_key: string
}

/** sysio.system::delsnapprov (action) */
export interface SysioSystemDelsnapprovAction {
  account: string
}

/** sysio.system::emission_config (type) */
export interface SysioSystemEmissionConfigType {
  t1_allocation: number | string
  t2_allocation: number | string
  t3_allocation: number | string
  t1_duration: number
  t2_duration: number
  t3_duration: number
  min_claimable: number | string
  t5_distributable: number | string
  t5_floor: number | string
  target_annual_decay_bps: number
  annual_initial_emission: number | string
  annual_max_emission: number | string
  annual_min_emission: number | string
  compute_bps: number
  capex_bps: number
  governance_bps: number
  producer_bps: number
  batch_op_bps: number
  standby_end_rank: number
  epoch_log_retention_count: number
  pay_cadence_epochs: number
}

/** sysio.system::emission_state (type) */
export interface SysioSystemEmissionStateType {
  node_rewards_start: string
}

/** sysio.system::epoch_info_result (type) */
export interface SysioSystemEpochInfoResultType {
  epoch_count: number | string
  last_epoch_index: number
  last_epoch_time: string
  last_epoch_emission: number | string
  total_distributed: number | string
  treasury_remaining: number | string
  next_emission_est: number | string
  seconds_until_next: number
}

/** sysio.system::epoch_log (type) */
export interface SysioSystemEpochLogType {
  sysio_epoch_index: number
  epoch_count: number | string
  timestamp: string
  total_emission: number | string
  compute_amount: number | string
  capex_amount: number | string
  governance_amount: number | string
  fee_distributed: number | string
}

/** sysio.system::epochlog_key (type) */
export interface SysioSystemEpochlogKeyType {
  sysio_epoch_index: number | string
}

/** sysio.system::fin_key_id_generator_info (type) */
export interface SysioSystemFinKeyIdGeneratorInfoType {
  next_finalizer_key_id: number | string
}

/** sysio.system::finalizer_auth_info (type) */
export interface SysioSystemFinalizerAuthInfoType {
  key_id: number | string
  fin_authority: SysioSystemFinalizerAuthorityType
}

/** sysio.system::finalizer_authority (type) */
export interface SysioSystemFinalizerAuthorityType {
  description: string
  weight: number | string
  public_key: string
}

/** sysio.system::finalizer_info (type) */
export interface SysioSystemFinalizerInfoType {
  finalizer_name: string
  active_key_id: number | string
  active_key_binary: string
  finalizer_key_count: number
}

/** sysio.system::finalizer_key_info (type) */
export interface SysioSystemFinalizerKeyInfoType {
  id: number | string
  finalizer_name: string
  finalizer_key: string
  finalizer_key_binary: string
}

/** sysio.system::finalizer_key_t (type) */
export interface SysioSystemFinalizerKeyTType {
  finalizer_name: number | string
}

/** sysio.system::finkey_key_t (type) */
export interface SysioSystemFinkeyKeyTType {
  id: number | string
}

/** sysio.system::fundclaim (action) */
export interface SysioSystemFundclaimAction {
  amount: number | string
}

/** sysio.system::getsnaphash (action) */
export interface SysioSystemGetsnaphashAction {
  block_num: number
}

/** sysio.system::init (action) */
export interface SysioSystemInitAction {
  version: number
  core: string
}

/** sysio.system::initt5 (action) */
export interface SysioSystemInitt5Action {
  start_time: string
}

/** sysio.system::key_weight (type) */
export interface SysioSystemKeyWeightType {
  key: string
  weight: number
}

/** sysio.system::last_prop_finalizers_info (type) */
export interface SysioSystemLastPropFinalizersInfoType {
  last_proposed_finalizers: SysioSystemFinalizerAuthInfoType[]
}

/** sysio.system::limitauthchg (action) */
export interface SysioSystemLimitauthchgAction {
  account: string
  allow_perms: string[]
  disallow_perms: string[]
}

/** sysio.system::linkauth (action) */
export interface SysioSystemLinkauthAction {
  account: string
  code: string
  type: string
  requirement: string
  authorized_by: unknown
}

/** sysio.system::newaccount (action) */
export interface SysioSystemNewaccountAction {
  creator: string
  name: string
  owner: SysioSystemAuthorityType
  active: SysioSystemAuthorityType
}

/** sysio.system::node_claim_result (type) */
export interface SysioSystemNodeClaimResultType {
  total_allocation: string
  claimed: string
  claimable: string
  can_claim: boolean
}

/** sysio.system::node_count_state (type) */
export interface SysioSystemNodeCountStateType {
  t1_count: number
  t2_count: number
  t3_count: number
}

/** sysio.system::node_owner_distribution (type) */
export interface SysioSystemNodeOwnerDistributionType {
  account_name: string
  total_allocation: string
  claimed: string
  total_duration: number
}

/** sysio.system::nodedist_key (type) */
export interface SysioSystemNodedistKeyType {
  account_name: number | string
}

/** sysio.system::onblock (action) */
export interface SysioSystemOnblockAction {
  header: SysioSystemBlockHeaderType
}

/** sysio.system::payepoch (action) */
export interface SysioSystemPayepochAction {
  epoch_index: number
  batch_op_groups: string[][]
  period_emission: number | string
}

/** sysio.system::permission_level (type) */
export interface SysioSystemPermissionLevelType {
  actor: string
  permission: string
}

/** sysio.system::permission_level_weight (type) */
export interface SysioSystemPermissionLevelWeightType {
  permission: SysioSystemPermissionLevelType
  weight: number
}

/** sysio.system::producer_authority (type) */
export interface SysioSystemProducerAuthorityType {
  producer_name: string
  authority: unknown
}

/** sysio.system::producer_info (type) */
export interface SysioSystemProducerInfoType {
  owner: string
  producer_key: string
  rank: number
  is_active: boolean
  url: string
  unpaid_blocks: number
  last_claim_time: string
  location: number
  producer_authority: unknown
  last_block_num: number
  current_round_blocks: number
  eligible_rounds: number
}

/** sysio.system::producer_key (type) */
export interface SysioSystemProducerKeyType {
  producer_name: string
  block_signing_key: string
}

/** sysio.system::producer_key_t (type) */
export interface SysioSystemProducerKeyTType {
  owner: number | string
}

/** sysio.system::producer_schedule (type) */
export interface SysioSystemProducerScheduleType {
  version: number
  producers: SysioSystemProducerKeyType[]
}

/** sysio.system::regfinkey (action) */
export interface SysioSystemRegfinkeyAction {
  finalizer_name: string
  finalizer_key: string
  proof_of_possession: string
}

/** sysio.system::regproducer (action) */
export interface SysioSystemRegproducerAction {
  producer: string
  producer_key: string
  url: string
  location: number
}

/** sysio.system::regproducer2 (action) */
export interface SysioSystemRegproducer2Action {
  producer: string
  producer_authority: unknown
  url: string
  location: number
}

/** sysio.system::regsnapprov (action) */
export interface SysioSystemRegsnapprovAction {
  producer: string
  snap_account: string
}

/** sysio.system::rmvproducer (action) */
export interface SysioSystemRmvproducerAction {
  producer: string
}

/** sysio.system::setabi (action) */
export interface SysioSystemSetabiAction {
  account: string
  abi: string
  memo: unknown
}

/** sysio.system::setacctcpu (action) */
export interface SysioSystemSetacctcpuAction {
  account: string
  cpu_weight?: number | string | null
}

/** sysio.system::setacctnet (action) */
export interface SysioSystemSetacctnetAction {
  account: string
  net_weight?: number | string | null
}

/** sysio.system::setacctram (action) */
export interface SysioSystemSetacctramAction {
  account: string
  ram_bytes?: number | string | null
}

/** sysio.system::setalimits (action) */
export interface SysioSystemSetalimitsAction {
  account: string
  ram_bytes: number | string
  net_weight: number | string
  cpu_weight: number | string
}

/** sysio.system::setcode (action) */
export interface SysioSystemSetcodeAction {
  account: string
  vmtype: number
  vmversion: number
  code: string
  memo: unknown
}

/** sysio.system::setemitcfg (action) */
export interface SysioSystemSetemitcfgAction {
  cfg: SysioSystemEmissionConfigType
}

/** sysio.system::setinittime (action) */
export interface SysioSystemSetinittimeAction {
  no_reward_init_time: string
}

/** sysio.system::setparams (action) */
export interface SysioSystemSetparamsAction {
  params: SysioSystemBlockchainParametersType
}

/** sysio.system::setpriv (action) */
export interface SysioSystemSetprivAction {
  account: string
  is_priv: number
}

/** sysio.system::setprodkeys (action) */
export interface SysioSystemSetprodkeysAction {
  schedule: SysioSystemProducerKeyType[]
}

/** sysio.system::setprods (action) */
export interface SysioSystemSetprodsAction {
  schedule: SysioSystemProducerAuthorityType[]
}

/** sysio.system::setram (action) */
export interface SysioSystemSetramAction {
  max_ram_size: number | string
}

/** sysio.system::setrank (action) */
export interface SysioSystemSetrankAction {
  producer: string
  rank: number
}

/** sysio.system::setsnpcfg (action) */
export interface SysioSystemSetsnpcfgAction {
  min_providers: number
  threshold_pct: number
}

/** sysio.system::snap_config (type) */
export interface SysioSystemSnapConfigType {
  min_providers: number
  threshold_pct: number
}

/** sysio.system::snap_provider (type) */
export interface SysioSystemSnapProviderType {
  snap_account: string
  producer: string
}

/** sysio.system::snap_provider_key_t (type) */
export interface SysioSystemSnapProviderKeyTType {
  snap_account: number | string
}

/** sysio.system::snap_record (type) */
export interface SysioSystemSnapRecordType {
  block_num: number
  block_id: string
  snapshot_hash: string
  attested_at_block: number
}

/** sysio.system::snap_record_key_t (type) */
export interface SysioSystemSnapRecordKeyTType {
  block_num: number | string
}

/** sysio.system::snap_vote (type) */
export interface SysioSystemSnapVoteType {
  id: number | string
  block_num: number
  block_id: string
  snapshot_hash: string
  voters: string[]
}

/** sysio.system::snap_vote_key_t (type) */
export interface SysioSystemSnapVoteKeyTType {
  id: number | string
}

/** sysio.system::sysio_global_state (type) */
export interface SysioSystemSysioGlobalStateType {
  max_ram_size: number | string
  total_ram_bytes_reserved: number | string
  last_producer_schedule_update: string
  last_pervote_bucket_fill: string
  total_unpaid_blocks: number
  last_producer_schedule_size: number
}

/** sysio.system::t5_state (type) */
export interface SysioSystemT5StateType {
  start_time: string
  epoch_count: number | string
  last_epoch_index: number
  last_epoch_time: string
  last_epoch_emission: number | string
  total_distributed: number | string
  pending_emission_amount: number | string
  period_start_epoch: number
  batch_group_epochs: number[]
  capital_shortfall_total: number | string
}

/** sysio.system::unlinkauth (action) */
export interface SysioSystemUnlinkauthAction {
  account: string
  code: string
  type: string
  authorized_by: unknown
}

/** sysio.system::unregprod (action) */
export interface SysioSystemUnregprodAction {
  producer: string
}

/** sysio.system::updateauth (action) */
export interface SysioSystemUpdateauthAction {
  account: string
  permission: string
  parent: string
  auth: SysioSystemAuthorityType
  authorized_by: unknown
}

/** sysio.system::viewemitcfg (action) */
export interface SysioSystemViewemitcfgAction {
}

/** sysio.system::viewepoch (action) */
export interface SysioSystemViewepochAction {
}

/** sysio.system::viewnodedist (action) */
export interface SysioSystemViewnodedistAction {
  account_name: string
}

/** sysio.system::votesnaphash (action) */
export interface SysioSystemVotesnaphashAction {
  snap_account: string
  block_id: string
  snapshot_hash: string
}

/** sysio.system::wasmcfg (action) */
export interface SysioSystemWasmcfgAction {
  settings: string
}

/** sysio.system::limit_auth_change (type) */
export interface SysioSystemLimitAuthChangeType {
  version: number
  account: string
  allow_perms: string[]
  disallow_perms: string[]
}

/** sysio.system::limitauthchg_key (type) */
export interface SysioSystemLimitauthchgKeyType {
  account: number | string
}

/** sysio.system::delpeerkey (action) */
export interface SysioSystemDelpeerkeyAction {
  proposer_finalizer_name: string
  key: string
}

/** sysio.system::getpeerkeys (action) */
export interface SysioSystemGetpeerkeysAction {
}

/** sysio.system::peer_key (type) */
export interface SysioSystemPeerKeyType {
  account: string
  data: unknown
}

/** sysio.system::peerkey_key (type) */
export interface SysioSystemPeerkeyKeyType {
  account: number | string
}

/** sysio.system::peerkeys_t (type) */
export interface SysioSystemPeerkeysTType {
  producer_name: string
  peer_key?: string | null
}

/** sysio.system::regpeerkey (action) */
export interface SysioSystemRegpeerkeyAction {
  proposer_finalizer_name: string
  key: string
}

/** sysio.system::v0_data (type) */
export interface SysioSystemV0DataType {
  pubkey?: string | null
}

/** sysio.system::addtrxp (action) */
export interface SysioSystemAddtrxpAction {
  receiver: string
  action_name: string
  match_type: SysioSystemTrxMatchType | keyof typeof SysioSystemTrxMatchType
  priority: number
}

/** sysio.system::deltrxp (action) */
export interface SysioSystemDeltrxpAction {
  priority: number
}

/** sysio.system::trx_prio (type) */
export interface SysioSystemTrxPrioType {
  priority: number
  receiver: string
  action_name: string
  match_type: SysioSystemTrxMatchType | keyof typeof SysioSystemTrxMatchType
}

/** sysio.system::trx_prio_global (type) */
export interface SysioSystemTrxPrioGlobalType {
  last_trx_priority_update: string
}

/** sysio.system::trxprio_key (type) */
export interface SysioSystemTrxprioKeyType {
  priority: number | string
}

/** sysio.system - action + table surface for the typed contract client. */
export interface SysioSystemContract {
  actions: {
    accrueepoch: SysioSystemAccrueepochAction
    actfinkey: SysioSystemActfinkeyAction
    activate: SysioSystemActivateAction
    addnodeowner: SysioSystemAddnodeownerAction
    claimnodedis: SysioSystemClaimnodedisAction
    deleteauth: SysioSystemDeleteauthAction
    delfinkey: SysioSystemDelfinkeyAction
    delsnapprov: SysioSystemDelsnapprovAction
    fundclaim: SysioSystemFundclaimAction
    getsnaphash: SysioSystemGetsnaphashAction
    init: SysioSystemInitAction
    initt5: SysioSystemInitt5Action
    limitauthchg: SysioSystemLimitauthchgAction
    linkauth: SysioSystemLinkauthAction
    newaccount: SysioSystemNewaccountAction
    onblock: SysioSystemOnblockAction
    payepoch: SysioSystemPayepochAction
    regfinkey: SysioSystemRegfinkeyAction
    regproducer: SysioSystemRegproducerAction
    regproducer2: SysioSystemRegproducer2Action
    regsnapprov: SysioSystemRegsnapprovAction
    rmvproducer: SysioSystemRmvproducerAction
    setabi: SysioSystemSetabiAction
    setacctcpu: SysioSystemSetacctcpuAction
    setacctnet: SysioSystemSetacctnetAction
    setacctram: SysioSystemSetacctramAction
    setalimits: SysioSystemSetalimitsAction
    setcode: SysioSystemSetcodeAction
    setemitcfg: SysioSystemSetemitcfgAction
    setinittime: SysioSystemSetinittimeAction
    setparams: SysioSystemSetparamsAction
    setpriv: SysioSystemSetprivAction
    setprodkeys: SysioSystemSetprodkeysAction
    setprods: SysioSystemSetprodsAction
    setram: SysioSystemSetramAction
    setrank: SysioSystemSetrankAction
    setsnpcfg: SysioSystemSetsnpcfgAction
    unlinkauth: SysioSystemUnlinkauthAction
    unregprod: SysioSystemUnregprodAction
    updateauth: SysioSystemUpdateauthAction
    viewemitcfg: SysioSystemViewemitcfgAction
    viewepoch: SysioSystemViewepochAction
    viewnodedist: SysioSystemViewnodedistAction
    votesnaphash: SysioSystemVotesnaphashAction
    wasmcfg: SysioSystemWasmcfgAction
    delpeerkey: SysioSystemDelpeerkeyAction
    getpeerkeys: SysioSystemGetpeerkeysAction
    regpeerkey: SysioSystemRegpeerkeyAction
    addtrxp: SysioSystemAddtrxpAction
    deltrxp: SysioSystemDeltrxpAction
  }
  tables: {
    abihash: SysioSystemAbiHashType
    blockinfo: SysioSystemBlockInfoRecordType
    emissionmngr: SysioSystemEmissionStateType
    emitcfg: SysioSystemEmissionConfigType
    epochlog: SysioSystemEpochLogType
    finalizers: SysioSystemFinalizerInfoType
    finkeyidgen: SysioSystemFinKeyIdGeneratorInfoType
    finkeys: SysioSystemFinalizerKeyInfoType
    global: SysioSystemSysioGlobalStateType
    lastpropfins: SysioSystemLastPropFinalizersInfoType
    nodecount: SysioSystemNodeCountStateType
    nodedist: SysioSystemNodeOwnerDistributionType
    producers: SysioSystemProducerInfoType
    snapconfig: SysioSystemSnapConfigType
    snapprovs: SysioSystemSnapProviderType
    snaprecords: SysioSystemSnapRecordType
    snapvotes: SysioSystemSnapVoteType
    t5state: SysioSystemT5StateType
    limitauthchg: SysioSystemLimitAuthChangeType
    peerkeys: SysioSystemPeerKeyType
    trxpglobal: SysioSystemTrxPrioGlobalType
    trxpriority: SysioSystemTrxPrioType
  }
}

// ── sysio.token ──

/** sysio.token::account (type) */
export interface SysioTokenAccountType {
  balance: string
}

/** sysio.token::acct_key (type) */
export interface SysioTokenAcctKeyType {
  sym_code: number | string
}

/** sysio.token::close (action) */
export interface SysioTokenCloseAction {
  owner: string
  symbol: string
}

/** sysio.token::create (action) */
export interface SysioTokenCreateAction {
  issuer: string
  maximum_supply: string
}

/** sysio.token::currency_stats (type) */
export interface SysioTokenCurrencyStatsType {
  supply: string
  max_supply: string
  issuer: string
}

/** sysio.token::issue (action) */
export interface SysioTokenIssueAction {
  to: string
  quantity: string
  memo: string
}

/** sysio.token::open (action) */
export interface SysioTokenOpenAction {
  owner: string
  symbol: string
  ram_payer: string
}

/** sysio.token::retire (action) */
export interface SysioTokenRetireAction {
  quantity: string
  memo: string
}

/** sysio.token::stat_key (type) */
export interface SysioTokenStatKeyType {
  sym_code: number | string
}

/** sysio.token::transfer (action) */
export interface SysioTokenTransferAction {
  from: string
  to: string
  quantity: string
  memo: string
}

/** sysio.token - action + table surface for the typed contract client. */
export interface SysioTokenContract {
  actions: {
    close: SysioTokenCloseAction
    create: SysioTokenCreateAction
    issue: SysioTokenIssueAction
    open: SysioTokenOpenAction
    retire: SysioTokenRetireAction
    transfer: SysioTokenTransferAction
  }
  tables: {
    accounts: SysioTokenAccountType
    stat: SysioTokenCurrencyStatsType
  }
}

// ── sysio.tokens ──

/** sysio.tokens::ChainKind (enum, int32) */
export enum SysioTokensChainkind {
  CHAIN_KIND_UNKNOWN = 0,
  CHAIN_KIND_WIRE = 1,
  CHAIN_KIND_EVM = 2,
  CHAIN_KIND_SVM = 3,
}

/** sysio.tokens::TokenKind (enum, int32) */
export enum SysioTokensTokenkind {
  TOKEN_KIND_UNKNOWN = 0,
  TOKEN_KIND_NATIVE = 1,
  TOKEN_KIND_ERC20 = 2,
  TOKEN_KIND_ERC721 = 3,
  TOKEN_KIND_ERC1155 = 4,
  TOKEN_KIND_SPL = 5,
  TOKEN_KIND_SPL_NFT = 6,
  TOKEN_KIND_LIQ = 7,
}

/** sysio.tokens::ChainAddress (type) */
export interface SysioTokensChainaddressType {
  kind: SysioTokensChainkind | keyof typeof SysioTokensChainkind
  address: string
}

/** sysio.tokens::activctok (action) */
export interface SysioTokensActivctokAction {
  chain_code: SysioTokensSlugNameType
  token_code: SysioTokensSlugNameType
}

/** sysio.tokens::activtoken (action) */
export interface SysioTokensActivtokenAction {
  code: SysioTokensSlugNameType
}

/** sysio.tokens::chain_token_key (type) */
export interface SysioTokensChainTokenKeyType {
  chain_code: SysioTokensSlugNameType
  token_code: SysioTokensSlugNameType
}

/** sysio.tokens::chain_token_row (type) */
export interface SysioTokensChainTokenRowType {
  chain_code: SysioTokensSlugNameType
  token_code: SysioTokensSlugNameType
  contract_addr: string
  is_native: boolean
  active: boolean
  registered_at_ms: number | string
  activated_at_ms: number | string
}

/** sysio.tokens::regctok (action) */
export interface SysioTokensRegctokAction {
  chain_code: SysioTokensSlugNameType
  token_code: SysioTokensSlugNameType
  contract_addr: string
  is_native: boolean
}

/** sysio.tokens::regtoken (action) */
export interface SysioTokensRegtokenAction {
  kind: SysioTokensTokenkind | keyof typeof SysioTokensTokenkind
  code: SysioTokensSlugNameType
  symbol_name: string
  description: string
  precision: number
  address: SysioTokensChainaddressType
}

/** sysio.tokens::slug_name (type) */
export interface SysioTokensSlugNameType {
  value: number | string
}

/** sysio.tokens::token_key (type) */
export interface SysioTokensTokenKeyType {
  code: SysioTokensSlugNameType
}

/** sysio.tokens::token_row (type) */
export interface SysioTokensTokenRowType {
  code: SysioTokensSlugNameType
  kind: SysioTokensTokenkind | keyof typeof SysioTokensTokenkind
  symbol_name: string
  description: string
  precision: number
  address: SysioTokensChainaddressType
  active: boolean
  registered_at_ms: number | string
  activated_at_ms: number | string
}

/** sysio.tokens - action + table surface for the typed contract client. */
export interface SysioTokensContract {
  actions: {
    activctok: SysioTokensActivctokAction
    activtoken: SysioTokensActivtokenAction
    regctok: SysioTokensRegctokAction
    regtoken: SysioTokensRegtokenAction
  }
  tables: {
    chaintokens: SysioTokensChainTokenRowType
    tokens: SysioTokensTokenRowType
  }
}

// ── sysio.uwrit ──

/** sysio.uwrit::AttestationType (enum, int32) */
export enum SysioUwritAttestationtype {
  ATTESTATION_TYPE_UNSPECIFIED = 0,
  ATTESTATION_TYPE_OPERATOR_ACTION = 2001,
  ATTESTATION_TYPE_STAKE = 3001,
  ATTESTATION_TYPE_UNSTAKE = 3002,
  ATTESTATION_TYPE_PRETOKEN_PURCHASE = 3004,
  ATTESTATION_TYPE_PRETOKEN_YIELD = 3006,
  ATTESTATION_TYPE_RESERVE_BALANCE_SHEET = 43520,
  ATTESTATION_TYPE_STAKE_UPDATE = 60928,
  ATTESTATION_TYPE_WIRE_TOKEN_PURCHASE = 60930,
  ATTESTATION_TYPE_CHALLENGE_RESPONSE = 60932,
  ATTESTATION_TYPE_SWAP_REQUEST = 60934,
  ATTESTATION_TYPE_SWAP_REMIT = 60944,
  ATTESTATION_TYPE_CHALLENGE_REQUEST = 60945,
  ATTESTATION_TYPE_OPERATORS = 60947,
  ATTESTATION_TYPE_BATCH_OPERATOR_GROUPS = 60943,
  ATTESTATION_TYPE_NODE_OWNER_REG = 60949,
  ATTESTATION_TYPE_STAKING_REWARD = 60950,
  ATTESTATION_TYPE_STAKE_RESULT = 60951,
  ATTESTATION_TYPE_ATTESTATION_PROCESSING_ERROR = 60952,
  ATTESTATION_TYPE_UNDERWRITE_INTENT_COMMIT = 60953,
  ATTESTATION_TYPE_SWAP_REVERT = 60955,
  ATTESTATION_TYPE_DEPOSIT_REVERT = 60956,
  ATTESTATION_TYPE_RESERVE_CREATE = 60958,
  ATTESTATION_TYPE_RESERVE_CREATE_CANCEL = 60959,
  ATTESTATION_TYPE_RESERVE_CREATE_CANCELLED = 60960,
  ATTESTATION_TYPE_RESERVE_READY = 60961,
  ATTESTATION_TYPE_EMISSIONS_BLOCKED = 60962,
}

/** sysio.uwrit::ChainKind (enum, int32) */
export enum SysioUwritChainkind {
  CHAIN_KIND_UNKNOWN = 0,
  CHAIN_KIND_WIRE = 1,
  CHAIN_KIND_EVM = 2,
  CHAIN_KIND_SVM = 3,
}

/** sysio.uwrit::UnderwriteRequestStatus (enum, int32) */
export enum SysioUwritUnderwriterequeststatus {
  UNDERWRITE_REQUEST_STATUS_PENDING = 0,
  UNDERWRITE_REQUEST_STATUS_CONFIRMED = 1,
  UNDERWRITE_REQUEST_STATUS_REJECTED = 2,
  UNDERWRITE_REQUEST_STATUS_COMPLETED = 3,
  UNDERWRITE_REQUEST_STATUS_EXPIRED = 4,
}

/** sysio.uwrit::UnderwriteStatus (enum, int32) */
export enum SysioUwritUnderwritestatus {
  UNDERWRITE_STATUS_INTENT_CREATED = 0,
  UNDERWRITE_STATUS_INTENT_SUBMITTED = 1,
  UNDERWRITE_STATUS_INTENT_CONFIRMED = 2,
  UNDERWRITE_STATUS_READY = 3,
  UNDERWRITE_STATUS_RELEASED = 5,
  UNDERWRITE_STATUS_SLASHED = 10,
  UNDERWRITE_STATUS_DISQUALIFIED = 11,
}

/** sysio.uwrit::chklocks (action) */
export interface SysioUwritChklocksAction {
}

/** sysio.uwrit::commit_entry (type) */
export interface SysioUwritCommitEntryType {
  underwriter: string
  source_received_at_ms: number | string
  source_outpost_id: number | string
  source_uic_bytes: string
  dest_received_at_ms: number | string
  dest_outpost_id: number | string
  dest_uic_bytes: string
  status: SysioUwritUnderwritestatus | keyof typeof SysioUwritUnderwritestatus
  reason: string
}

/** sysio.uwrit::createuwreq (action) */
export interface SysioUwritCreateuwreqAction {
  attestation_id: number | string
  type: SysioUwritAttestationtype | keyof typeof SysioUwritAttestationtype
  chain_code: number | string
  data: string
}

/** sysio.uwrit::drainfwq (action) */
export interface SysioUwritDrainfwqAction {
}

/** sysio.uwrit::fromwire_q (type) */
export interface SysioUwritFromwireQType {
  id: number | string
  user: string
  wire_amount: number | string
  dst_chain_code: SysioUwritSlugNameType
  dst_token_code: SysioUwritSlugNameType
  dst_reserve_code: SysioUwritSlugNameType
  target_amount: number | string
  variance_tolerance_bps: number
  recipient_kind: SysioUwritChainkind | keyof typeof SysioUwritChainkind
  recipient_addr: string
  created_at_epoch: number
}

/** sysio.uwrit::fw_key (type) */
export interface SysioUwritFwKeyType {
  id: number | string
}

/** sysio.uwrit::id_key (type) */
export interface SysioUwritIdKeyType {
  id: number | string
}

/** sysio.uwrit::lock_entry (type) */
export interface SysioUwritLockEntryType {
  lock_id: number | string
  uwreq_id: number | string
  underwriter: string
  chain_code: SysioUwritSlugNameType
  token_code: SysioUwritSlugNameType
  reserve_code: SysioUwritSlugNameType
  amount: number | string
  created_at_ms: number | string
  expires_at_ms: number | string
}

/** sysio.uwrit::lock_key (type) */
export interface SysioUwritLockKeyType {
  lock_id: number | string
}

/** sysio.uwrit::rcrdcommit (action) */
export interface SysioUwritRcrdcommitAction {
  uwreq_id: number | string
  underwriter: string
  chain_code: number | string
  from_chain_code: SysioUwritSlugNameType
  from_token_code: SysioUwritSlugNameType
  reserve_code: SysioUwritSlugNameType
  uic_bytes: string
}

/** sysio.uwrit::setconfig (action) */
export interface SysioUwritSetconfigAction {
  fee_bps: number
  collateral_lock_duration_ms: number | string
  min_fromwire_amount: number | string
  fromwire_revert_fee_bps: number
}

/** sysio.uwrit::slug_name (type) */
export interface SysioUwritSlugNameType {
  value: number | string
}

/** sysio.uwrit::sumlocks (action) */
export interface SysioUwritSumlocksAction {
  underwriter: string
  chain_code: SysioUwritSlugNameType
  token_code: SysioUwritSlugNameType
}

/** sysio.uwrit::swapfromwire (action) */
export interface SysioUwritSwapfromwireAction {
  user: string
  wire_amount: number | string
  dst_chain_code: SysioUwritSlugNameType
  dst_token_code: SysioUwritSlugNameType
  dst_reserve_code: SysioUwritSlugNameType
  target_amount: number | string
  target_tolerance_bps: number
  recipient_kind: SysioUwritChainkind | keyof typeof SysioUwritChainkind
  recipient_addr: string
}

/** sysio.uwrit::uw_config (type) */
export interface SysioUwritUwConfigType {
  fee_bps: number
  collateral_lock_duration_ms: number | string
  min_fromwire_amount: number | string
  fromwire_revert_fee_bps: number
}

/** sysio.uwrit::uw_counters (type) */
export interface SysioUwritUwCountersType {
  next_lock_id: number | string
  next_fromwire_seq: number | string
}

/** sysio.uwrit::uw_request_t (type) */
export interface SysioUwritUwRequestTType {
  id: number | string
  type: SysioUwritAttestationtype | keyof typeof SysioUwritAttestationtype
  status: SysioUwritUnderwriterequeststatus | keyof typeof SysioUwritUnderwriterequeststatus
  src_chain_code: SysioUwritSlugNameType
  src_token_code: SysioUwritSlugNameType
  src_reserve_code: SysioUwritSlugNameType
  src_amount: number | string
  dst_chain_code: SysioUwritSlugNameType
  dst_token_code: SysioUwritSlugNameType
  dst_reserve_code: SysioUwritSlugNameType
  dst_amount: number | string
  variance_tolerance_bps: number
  source_tx_id: string
  depositor: string
  commits_by: SysioUwritCommitEntryType[]
  winner: string
  committed_at_ms: number | string
  settled_at_ms: number | string
  expires_at_epoch: number
  attestation_inbound_data: string
  attestation_outbound_data: string
}

/** sysio.uwrit - action + table surface for the typed contract client. */
export interface SysioUwritContract {
  actions: {
    chklocks: SysioUwritChklocksAction
    createuwreq: SysioUwritCreateuwreqAction
    drainfwq: SysioUwritDrainfwqAction
    rcrdcommit: SysioUwritRcrdcommitAction
    setconfig: SysioUwritSetconfigAction
    sumlocks: SysioUwritSumlocksAction
    swapfromwire: SysioUwritSwapfromwireAction
  }
  tables: {
    fwqueue: SysioUwritFromwireQType
    locks: SysioUwritLockEntryType
    uwconfig: SysioUwritUwConfigType
    uwcounters: SysioUwritUwCountersType
    uwreqs: SysioUwritUwRequestTType
  }
}

// ── sysio.wrap ──

/** sysio.wrap::action (type) */
export interface SysioWrapActionType {
  account: string
  name: string
  authorization: SysioWrapPermissionLevelType[]
  data: string
}

/** sysio.wrap::exec (action) */
export interface SysioWrapExecAction {
  executer: string
  trx: SysioWrapTransactionType
}

/** sysio.wrap::extension (type) */
export interface SysioWrapExtensionType {
  type: number
  data: string
}

/** sysio.wrap::permission_level (type) */
export interface SysioWrapPermissionLevelType {
  actor: string
  permission: string
}

/** sysio.wrap::transaction (type) */
export interface SysioWrapTransactionType {
  context_free_actions: SysioWrapActionType[]
  actions: SysioWrapActionType[]
  transaction_extensions: SysioWrapExtensionType[]
}

/** sysio.wrap::transaction_header (type) */
export interface SysioWrapTransactionHeaderType {
  expiration: string
  ref_block_num: number
  ref_block_prefix: number
  max_net_usage_words: number
  max_cpu_usage_ms: number
  delay_sec: number
}

/** sysio.wrap - action + table surface for the typed contract client. */
export interface SysioWrapContract {
  actions: {
    exec: SysioWrapExecAction
  }
  tables: {
  }
}

// ── contract registry ──

/** Short contract name - key into SysioContractMapping / SysioContractAccount. */
export enum SysioContractName {
  authex = "authex",
  bios = "bios",
  chains = "chains",
  chalg = "chalg",
  dclaim = "dclaim",
  epoch = "epoch",
  msgch = "msgch",
  msig = "msig",
  opreg = "opreg",
  reserv = "reserv",
  roa = "roa",
  system = "system",
  token = "token",
  tokens = "tokens",
  uwrit = "uwrit",
  wrap = "wrap",
}

/** On-chain account per contract (default sysio.<name>; system/bios -> sysio). */
export const SysioContractAccount: Record<SysioContractName, string> = {
  [SysioContractName.authex]: "sysio.authex",
  [SysioContractName.bios]: "sysio",
  [SysioContractName.chains]: "sysio.chains",
  [SysioContractName.chalg]: "sysio.chalg",
  [SysioContractName.dclaim]: "sysio.dclaim",
  [SysioContractName.epoch]: "sysio.epoch",
  [SysioContractName.msgch]: "sysio.msgch",
  [SysioContractName.msig]: "sysio.msig",
  [SysioContractName.opreg]: "sysio.opreg",
  [SysioContractName.reserv]: "sysio.reserv",
  [SysioContractName.roa]: "sysio.roa",
  [SysioContractName.system]: "sysio",
  [SysioContractName.token]: "sysio.token",
  [SysioContractName.tokens]: "sysio.tokens",
  [SysioContractName.uwrit]: "sysio.uwrit",
  [SysioContractName.wrap]: "sysio.wrap",
}

/** Each contract -> its action+table surface, for the typed contract client. */
export interface SysioContractMapping {
  [SysioContractName.authex]: SysioAuthexContract
  [SysioContractName.bios]: SysioBiosContract
  [SysioContractName.chains]: SysioChainsContract
  [SysioContractName.chalg]: SysioChalgContract
  [SysioContractName.dclaim]: SysioDclaimContract
  [SysioContractName.epoch]: SysioEpochContract
  [SysioContractName.msgch]: SysioMsgchContract
  [SysioContractName.msig]: SysioMsigContract
  [SysioContractName.opreg]: SysioOpregContract
  [SysioContractName.reserv]: SysioReservContract
  [SysioContractName.roa]: SysioRoaContract
  [SysioContractName.system]: SysioSystemContract
  [SysioContractName.token]: SysioTokenContract
  [SysioContractName.tokens]: SysioTokensContract
  [SysioContractName.uwrit]: SysioUwritContract
  [SysioContractName.wrap]: SysioWrapContract
}

/** Runtime action/table names + account per contract (the typed client validates against this). */
export interface SysioContractDefinition<Name extends SysioContractName> {
  readonly name: Name
  readonly account: string
  readonly actions: ReadonlyArray<string>
  readonly tables: ReadonlyArray<string>
}
export const SysioContractDefinitions: {
  readonly [Name in SysioContractName]: SysioContractDefinition<Name>
} = {
  [SysioContractName.authex]: { name: SysioContractName.authex, account: "sysio.authex", actions: ["clearlinks", "createlink", "recordlink"], tables: ["links"] },
  [SysioContractName.bios]: { name: SysioContractName.bios, account: "sysio", actions: ["activate", "deleteauth", "linkauth", "newaccount", "reqactivated", "reqauth", "setabi", "setalimits", "setcode", "setfinalizer", "setparams", "setpriv", "setprodkeys", "setprods", "unlinkauth", "updateauth"], tables: ["abihash"] },
  [SysioContractName.chains]: { name: SysioContractName.chains, account: "sysio.chains", actions: ["activchain", "regchain"], tables: ["chains"] },
  [SysioContractName.chalg]: { name: SysioContractName.chalg, account: "sysio.chalg", actions: ["chkdispute", "opendispute", "slashop", "votedispute"], tables: ["disputes", "disputevote"] },
  [SysioContractName.dclaim]: { name: SysioContractName.dclaim, account: "sysio.dclaim", actions: ["claim", "flushexpired", "importdone", "importseed", "linkswept", "onreward", "setclmwindow", "setconfig"], tables: ["capcfg", "capcounters", "pclaims", "rwdcursors", "unmapped"] },
  [SysioContractName.epoch]: { name: SysioContractName.epoch, account: "sysio.epoch", actions: ["advance", "pause", "schbatchgps", "setconfig", "unpause"], tables: ["blocklog", "epochcfg", "epochstate"] },
  [SysioContractName.msgch]: { name: SysioContractName.msgch, account: "sysio.msgch", actions: ["bootstrap", "buildenv", "chkcons", "deliver", "evalcons", "queueout", "resolvedisp"], tables: ["attestations", "attseq", "envelopes", "envlog", "messages", "outenvelopes", "outpcons"] },
  [SysioContractName.msig]: { name: SysioContractName.msig, account: "sysio.msig", actions: ["approve", "cancel", "exec", "getproposal", "invalidate", "propose", "unapprove"], tables: ["approvals", "approvals2", "invals", "propchunks", "proposal"] },
  [SysioContractName.opreg]: { name: SysioContractName.opreg, account: "sysio.opreg", actions: ["available", "cancelwtdw", "deposit", "depositinle", "flushwtdw", "processbatch", "processprod", "processuw", "prune", "recorddel", "regoperator", "releaselock", "setconfig", "slash", "termcheck", "terminate", "withdraw", "withdrawinle"], tables: ["dellog", "opconfig", "opcounters", "operators", "wtdwqueue"] },
  [SysioContractName.reserv]: { name: SysioContractName.reserv, account: "sysio.reserv", actions: ["applyfromwire", "applyswap", "debit", "drainrewards", "matchreserve", "oncnclrsv", "oncrtreserve", "paywire", "refundwire", "regreserve", "rewardbal", "swapquote"], tables: ["reserves", "rewardbkt"] },
  [SysioContractName.roa]: { name: SysioContractName.roa, account: "sysio.roa", actions: ["activateroa", "addpolicy", "expandpolicy", "extendpolicy", "forcereg", "giftram", "newnameduser", "newuser", "nodeownreg", "reducepolicy", "setbyteprice", "setsysabi", "setsyscode"], tables: ["nodeownerreg", "nodeowners", "policies", "reslimit", "roastate", "sponsorcount", "sponsors"] },
  [SysioContractName.system]: { name: SysioContractName.system, account: "sysio", actions: ["accrueepoch", "actfinkey", "activate", "addnodeowner", "claimnodedis", "deleteauth", "delfinkey", "delsnapprov", "fundclaim", "getsnaphash", "init", "initt5", "limitauthchg", "linkauth", "newaccount", "onblock", "payepoch", "regfinkey", "regproducer", "regproducer2", "regsnapprov", "rmvproducer", "setabi", "setacctcpu", "setacctnet", "setacctram", "setalimits", "setcode", "setemitcfg", "setinittime", "setparams", "setpriv", "setprodkeys", "setprods", "setram", "setrank", "setsnpcfg", "unlinkauth", "unregprod", "updateauth", "viewemitcfg", "viewepoch", "viewnodedist", "votesnaphash", "wasmcfg", "delpeerkey", "getpeerkeys", "regpeerkey", "addtrxp", "deltrxp"], tables: ["abihash", "blockinfo", "emissionmngr", "emitcfg", "epochlog", "finalizers", "finkeyidgen", "finkeys", "global", "lastpropfins", "nodecount", "nodedist", "producers", "snapconfig", "snapprovs", "snaprecords", "snapvotes", "t5state", "limitauthchg", "peerkeys", "trxpglobal", "trxpriority"] },
  [SysioContractName.token]: { name: SysioContractName.token, account: "sysio.token", actions: ["close", "create", "issue", "open", "retire", "transfer"], tables: ["accounts", "stat"] },
  [SysioContractName.tokens]: { name: SysioContractName.tokens, account: "sysio.tokens", actions: ["activctok", "activtoken", "regctok", "regtoken"], tables: ["chaintokens", "tokens"] },
  [SysioContractName.uwrit]: { name: SysioContractName.uwrit, account: "sysio.uwrit", actions: ["chklocks", "createuwreq", "drainfwq", "rcrdcommit", "setconfig", "sumlocks", "swapfromwire"], tables: ["fwqueue", "locks", "uwconfig", "uwcounters", "uwreqs"] },
  [SysioContractName.wrap]: { name: SysioContractName.wrap, account: "sysio.wrap", actions: ["exec"], tables: [] },
}

