// noinspection SpellCheckingInspection
/**
 * Auto-generated TypeScript types for Wire system contracts.
 * Generated by generate-system-contract-types.py
 *
 * Property naming style: snake
 */

/** Extended asset type. */
export interface ExtendedAsset {
  quantity: string
  contract: string
}

// ── sysio.authex ──

/** sysio.authex::chain_kind_t (enum, uint8) */
export enum SysioAuthexChainKindType {
  unknown = 0,
  wire = 1,
  ethereum = 2,
  solana = 3,
  sui = 4,
}

/** sysio.authex::clearlinks (action) */
export interface SysioAuthexClearlinksAction {
}

/** sysio.authex::createlink (action) */
export interface SysioAuthexCreatelinkAction {
  chain_kind: SysioAuthexChainKindType
  account: string
  sig: string
  pub_key: string
  nonce: number
}

/** sysio.authex::links_s (type) */
export interface SysioAuthexLinksSType {
  key: number
  username: string
  chain_kind: SysioAuthexChainKindType
  pub_key: string
}

// ── sysio.bios ──

/** sysio.bios::abi_hash (type) */
export interface SysioBiosAbiHashType {
  owner: string
  hash: string
}

/** sysio.bios::activate (action) */
export interface SysioBiosActivateAction {
  feature_digest: string
}

/** sysio.bios::authority (type) */
export interface SysioBiosAuthorityType {
  threshold: number
  keys: SysioBiosKeyWeightType[]
  accounts: SysioBiosPermissionLevelWeightType[]
}

/** sysio.bios::block_signing_authority_v0 (type) */
export interface SysioBiosBlockSigningAuthorityV0Type {
  threshold: number
  keys: SysioBiosKeyWeightType[]
}

/** sysio.bios::blockchain_parameters (type) */
export interface SysioBiosBlockchainParametersType {
  max_block_net_usage: number
  target_block_net_usage_pct: number
  max_transaction_net_usage: number
  base_per_transaction_net_usage: number
  net_usage_leeway: number
  context_free_discount_net_usage_num: number
  context_free_discount_net_usage_den: number
  max_block_cpu_usage: number
  target_block_cpu_usage_pct: number
  max_transaction_cpu_usage: number
  min_transaction_cpu_usage: number
  max_transaction_lifetime: number
  max_transaction_delay: number
  max_inline_action_size: number
  max_inline_action_depth: number
  max_authority_depth: number
  max_action_return_value_size: number
  max_kv_key_size: number
  max_kv_value_size: number
  max_kv_secondary_key_size: number
}

/** sysio.bios::deleteauth (action) */
export interface SysioBiosDeleteauthAction {
  account: string
  permission: string
}

/** sysio.bios::finalizer_authority (type) */
export interface SysioBiosFinalizerAuthorityType {
  description: string
  weight: number
  public_key: string
  pop: string
}

/** sysio.bios::finalizer_policy (type) */
export interface SysioBiosFinalizerPolicyType {
  threshold: number
  finalizers: SysioBiosFinalizerAuthorityType[]
}

/** sysio.bios::key_weight (type) */
export interface SysioBiosKeyWeightType {
  key: string
  weight: number
}

/** sysio.bios::linkauth (action) */
export interface SysioBiosLinkauthAction {
  account: string
  code: string
  type: string
  requirement: string
}

/** sysio.bios::newaccount (action) */
export interface SysioBiosNewaccountAction {
  creator: string
  name: string
  owner: SysioBiosAuthorityType
  active: SysioBiosAuthorityType
}

/** sysio.bios::permission_level (type) */
export interface SysioBiosPermissionLevelType {
  actor: string
  permission: string
}

/** sysio.bios::permission_level_weight (type) */
export interface SysioBiosPermissionLevelWeightType {
  permission: SysioBiosPermissionLevelType
  weight: number
}

/** sysio.bios::producer_authority (type) */
export interface SysioBiosProducerAuthorityType {
  producer_name: string
  authority: unknown
}

/** sysio.bios::producer_key (type) */
export interface SysioBiosProducerKeyType {
  producer_name: string
  block_signing_key: string
}

/** sysio.bios::reqactivated (action) */
export interface SysioBiosReqactivatedAction {
  feature_digest: string
}

/** sysio.bios::reqauth (action) */
export interface SysioBiosReqauthAction {
  from: string
}

/** sysio.bios::setabi (action) */
export interface SysioBiosSetabiAction {
  account: string
  abi: string
}

/** sysio.bios::setalimits (action) */
export interface SysioBiosSetalimitsAction {
  account: string
  ram_bytes: number
  net_weight: number
  cpu_weight: number
}

/** sysio.bios::setcode (action) */
export interface SysioBiosSetcodeAction {
  account: string
  vmtype: number
  vmversion: number
  code: string
}

/** sysio.bios::setfinalizer (action) */
export interface SysioBiosSetfinalizerAction {
  finalizer_policy: SysioBiosFinalizerPolicyType
}

/** sysio.bios::setparams (action) */
export interface SysioBiosSetparamsAction {
  params: SysioBiosBlockchainParametersType
}

/** sysio.bios::setpriv (action) */
export interface SysioBiosSetprivAction {
  account: string
  is_priv: number
}

/** sysio.bios::setprodkeys (action) */
export interface SysioBiosSetprodkeysAction {
  schedule: SysioBiosProducerKeyType[]
}

/** sysio.bios::setprods (action) */
export interface SysioBiosSetprodsAction {
  schedule: SysioBiosProducerAuthorityType[]
}

/** sysio.bios::unlinkauth (action) */
export interface SysioBiosUnlinkauthAction {
  account: string
  code: string
  type: string
}

/** sysio.bios::updateauth (action) */
export interface SysioBiosUpdateauthAction {
  account: string
  permission: string
  parent: string
  auth: SysioBiosAuthorityType
}

// ── sysio.chalg ──

/** sysio.chalg::ChallengeStatus (enum, int32) */
export enum SysioChalgChallengestatus {
  CHALLENGE_STATUS_CHALLENGE_SENT = 0,
  CHALLENGE_STATUS_RESPONSE_RECEIVED = 1,
  CHALLENGE_STATUS_RESOLVED = 2,
  CHALLENGE_STATUS_ESCALATED = 3,
}

/** sysio.chalg::challenge_entry (type) */
export interface SysioChalgChallengeEntryType {
  id: number
  chain_request_id: number
  epoch_index: number
  round: number
  status: SysioChalgChallengestatus
  challenge_hash: string
  response_hash: string
  correct_operators: string[]
  faulty_operators: string[]
  challenged_at: string
  responded_at: string
}

/** sysio.chalg::enforce (action) */
export interface SysioChalgEnforceAction {
  resolution_id: number
}

/** sysio.chalg::escalate (action) */
export interface SysioChalgEscalateAction {
  challenge_id: number
}

/** sysio.chalg::initchal (action) */
export interface SysioChalgInitchalAction {
  chain_req_id: number
}

/** sysio.chalg::manual_resolution (type) */
export interface SysioChalgManualResolutionType {
  id: number
  challenge_id: number
  original_chain_hash: string
  round1_chain_hash: string
  round2_chain_hash: string
  msig_proposal: string
  is_resolved: boolean
}

/** sysio.chalg::slashop (action) */
export interface SysioChalgSlashopAction {
  operator_acct: string
  reason: string
}

/** sysio.chalg::submitres (action) */
export interface SysioChalgSubmitresAction {
  submitter: string
  challenge_id: number
  orig_hash: string
  r1_hash: string
  r2_hash: string
}

/** sysio.chalg::submitresp (action) */
export interface SysioChalgSubmitrespAction {
  challenge_id: number
  response_hash: string
  correct_ops: string[]
  faulty_ops: string[]
}

// ── sysio.epoch ──

/** sysio.epoch::ChainKind (enum, int32) */
export enum SysioEpochChainkind {
  CHAIN_KIND_UNKNOWN = 0,
  CHAIN_KIND_WIRE = 1,
  CHAIN_KIND_ETHEREUM = 2,
  CHAIN_KIND_SOLANA = 3,
  CHAIN_KIND_SUI = 4,
}

/** sysio.epoch::advance (action) */
export interface SysioEpochAdvanceAction {
}

/** sysio.epoch::epoch_config (type) */
export interface SysioEpochEpochConfigType {
  epoch_duration_sec: number
  operators_per_epoch: number
  batch_operator_minimum_active: number
  batch_op_groups: number
  attestation_retention_epoch_count: number
}

/** sysio.epoch::epoch_state (type) */
export interface SysioEpochEpochStateType {
  current_epoch_index: number
  current_epoch_start: string
  next_epoch_start: string
  current_batch_op_group: number
  batch_op_groups: string[][]
  last_consensus_hash: string
  is_paused: boolean
}

/** sysio.epoch::initgroups (action) */
export interface SysioEpochInitgroupsAction {
}

/** sysio.epoch::outpost_info (type) */
export interface SysioEpochOutpostInfoType {
  id: number
  chain_kind: SysioEpochChainkind
  chain_id: number
  last_inbound_msg_id: string
  last_outbound_msg_id: string
  last_inbound_epoch: number
  last_outbound_epoch: number
}

/** sysio.epoch::pause (action) */
export interface SysioEpochPauseAction {
}

/** sysio.epoch::regoutpost (action) */
export interface SysioEpochRegoutpostAction {
  chain_kind: SysioEpochChainkind
  chain_id: number
}

/** sysio.epoch::setconfig (action) */
export interface SysioEpochSetconfigAction {
  epoch_duration_sec: number
  operators_per_epoch: number
  batch_operator_minimum_active: number
  batch_op_groups: number
  attestation_retention_epoch_count: number
}

/** sysio.epoch::unpause (action) */
export interface SysioEpochUnpauseAction {
}

// ── sysio.msgch ──

/** sysio.msgch::AttestationStatus (enum, int32) */
export enum SysioMsgchAttestationstatus {
  ATTESTATION_STATUS_PENDING = 0,
  ATTESTATION_STATUS_READY = 1,
  ATTESTATION_STATUS_PROCESSED = 2,
}

/** sysio.msgch::AttestationType (enum, int32) */
export enum SysioMsgchAttestationtype {
  ATTESTATION_TYPE_UNSPECIFIED = 0,
  ATTESTATION_TYPE_OPERATOR_ACTION = 2001,
  ATTESTATION_TYPE_STAKE = 3001,
  ATTESTATION_TYPE_UNSTAKE = 3002,
  ATTESTATION_TYPE_PRETOKEN_PURCHASE = 3004,
  ATTESTATION_TYPE_PRETOKEN_YIELD = 3006,
  ATTESTATION_TYPE_RESERVE_BALANCE_SHEET = 43520,
  ATTESTATION_TYPE_STAKE_UPDATE = 60928,
  ATTESTATION_TYPE_NATIVE_YIELD_REWARD = 60929,
  ATTESTATION_TYPE_WIRE_TOKEN_PURCHASE = 60930,
  ATTESTATION_TYPE_CHALLENGE_RESPONSE = 60932,
  ATTESTATION_TYPE_SLASH_OPERATOR = 60933,
  ATTESTATION_TYPE_SWAP = 60934,
  ATTESTATION_TYPE_UNDERWRITE_INTENT = 60935,
  ATTESTATION_TYPE_UNDERWRITE_CONFIRM = 60936,
  ATTESTATION_TYPE_UNDERWRITE_REJECT = 60937,
  ATTESTATION_TYPE_UNDERWRITE_UNLOCK = 60938,
  ATTESTATION_TYPE_REMIT = 60944,
  ATTESTATION_TYPE_CHALLENGE_REQUEST = 60945,
  ATTESTATION_TYPE_EPOCH_SYNC = 60946,
  ATTESTATION_TYPE_ROSTER_UPDATE = 60947,
  ATTESTATION_TYPE_REMIT_CONFIRM = 60948,
  ATTESTATION_TYPE_BATCH_OPERATOR_NEXT_GROUP = 60943,
  ATTESTATION_TYPE_NODE_OWNER_REG = 60949,
  ATTESTATION_TYPE_STAKING_REWARD = 60950,
  ATTESTATION_TYPE_STAKE_RESULT = 60951,
  ATTESTATION_TYPE_ATTESTATION_PROCESSING_ERROR = 60952,
}

/** sysio.msgch::ChainKind (enum, int32) */
export enum SysioMsgchChainkind {
  CHAIN_KIND_UNKNOWN = 0,
  CHAIN_KIND_WIRE = 1,
  CHAIN_KIND_ETHEREUM = 2,
  CHAIN_KIND_SOLANA = 3,
  CHAIN_KIND_SUI = 4,
}

/** sysio.msgch::EnvelopeStatus (enum, int32) */
export enum SysioMsgchEnvelopestatus {
  ENVELOPE_STATUS_PENDING_DELIVERY = 0,
  ENVELOPE_STATUS_DELIVERED = 1,
  ENVELOPE_STATUS_CONFIRMED = 2,
}

/** sysio.msgch::MessageDirection (enum, int32) */
export enum SysioMsgchMessagedirection {
  MESSAGE_DIRECTION_INBOUND = 0,
  MESSAGE_DIRECTION_OUTBOUND = 1,
}

/** sysio.msgch::MessageStatus (enum, int32) */
export enum SysioMsgchMessagestatus {
  MESSAGE_STATUS_PENDING = 0,
  MESSAGE_STATUS_READY = 1,
  MESSAGE_STATUS_PROCESSED = 2,
  MESSAGE_STATUS_CANCELLED = 3,
}

/** sysio.msgch::attestation_entry (type) */
export interface SysioMsgchAttestationEntryType {
  id: number
  outpost_id: number
  epoch_index: number
  type: SysioMsgchAttestationtype
  status: SysioMsgchAttestationstatus
  data: string
  pending_timestamp: number
  ready_timestamp: number
  processed_timestamp: number
}

/** sysio.msgch::buildenv (action) */
export interface SysioMsgchBuildenvAction {
  outpost_id: number
}

/** sysio.msgch::cleanup (action) */
export interface SysioMsgchCleanupAction {
  before_epoch: number
}

/** sysio.msgch::deliver (action) */
export interface SysioMsgchDeliverAction {
  batch_op_name: string
  outpost_id: number
  data: string
}

/** sysio.msgch::envelope_entry (type) */
export interface SysioMsgchEnvelopeEntryType {
  id: number
  outpost_id: number
  epoch_index: number
  batch_op_name: string
  chain_kind: SysioMsgchChainkind
  checksum: string
  raw_data: string
  received_at: string
}

/** sysio.msgch::evalcons (action) */
export interface SysioMsgchEvalconsAction {
  outpost_id: number
  epoch_index: number
}

/** sysio.msgch::message_entry (type) */
export interface SysioMsgchMessageEntryType {
  id: number
  outpost_id: number
  epoch_index: number
  message_id: string
  previous_message_id: string
  direction: SysioMsgchMessagedirection
  status: SysioMsgchMessagestatus
  raw_payload: string
  received_at: string
  processed_at: string
}

/** sysio.msgch::outbound_envelope (type) */
export interface SysioMsgchOutboundEnvelopeType {
  id: number
  outpost_id: number
  epoch_index: number
  envelope_hash: string
  merkle_root: string
  start_message_id: string
  end_message_id: string
  status: SysioMsgchEnvelopestatus
  raw_envelope: string
}

/** sysio.msgch::queueout (action) */
export interface SysioMsgchQueueoutAction {
  outpost_id: number
  attest_type: SysioMsgchAttestationtype
  data: string
}

// ── sysio.msig ──

/** sysio.msig::action (type) */
export interface SysioMsigActionType {
  account: string
  name: string
  authorization: SysioMsigPermissionLevelType[]
  data: string
}

/** sysio.msig::approval (type) */
export interface SysioMsigApprovalType {
  level: SysioMsigPermissionLevelType
  time: string
}

/** sysio.msig::approvals_info (type) */
export interface SysioMsigApprovalsInfoType {
  version: number
  proposal_name: string
  requested_approvals: SysioMsigApprovalType[]
  provided_approvals: SysioMsigApprovalType[]
}

/** sysio.msig::approve (action) */
export interface SysioMsigApproveAction {
  proposer: string
  proposal_name: string
  level: SysioMsigPermissionLevelType
  proposal_hash: unknown
}

/** sysio.msig::cancel (action) */
export interface SysioMsigCancelAction {
  proposer: string
  proposal_name: string
  canceler: string
}

/** sysio.msig::exec (action) */
export interface SysioMsigExecAction {
  proposer: string
  proposal_name: string
  executer: string
}

/** sysio.msig::extension (type) */
export interface SysioMsigExtensionType {
  type: number
  data: string
}

/** sysio.msig::invalidate (action) */
export interface SysioMsigInvalidateAction {
  account: string
}

/** sysio.msig::invalidation (type) */
export interface SysioMsigInvalidationType {
  account: string
  last_invalidation_time: string
}

/** sysio.msig::old_approvals_info (type) */
export interface SysioMsigOldApprovalsInfoType {
  proposal_name: string
  requested_approvals: SysioMsigPermissionLevelType[]
  provided_approvals: SysioMsigPermissionLevelType[]
}

/** sysio.msig::permission_level (type) */
export interface SysioMsigPermissionLevelType {
  actor: string
  permission: string
}

/** sysio.msig::proposal (type) */
export interface SysioMsigProposalType {
  proposal_name: string
  packed_transaction: string
  earliest_exec_time: unknown
}

/** sysio.msig::propose (action) */
export interface SysioMsigProposeAction {
  proposer: string
  proposal_name: string
  requested: SysioMsigPermissionLevelType[]
  trx: SysioMsigTransactionType
}

/** sysio.msig::transaction (type) */
export interface SysioMsigTransactionType {
  context_free_actions: SysioMsigActionType[]
  actions: SysioMsigActionType[]
  transaction_extensions: SysioMsigExtensionType[]
}

/** sysio.msig::transaction_header (type) */
export interface SysioMsigTransactionHeaderType {
  expiration: string
  ref_block_num: number
  ref_block_prefix: number
  max_net_usage_words: number
  max_cpu_usage_ms: number
  delay_sec: number
}

/** sysio.msig::unapprove (action) */
export interface SysioMsigUnapproveAction {
  proposer: string
  proposal_name: string
  level: SysioMsigPermissionLevelType
}

// ── sysio.opreg ──

/** sysio.opreg::ChainKind (enum, int32) */
export enum SysioOpregChainkind {
  CHAIN_KIND_UNKNOWN = 0,
  CHAIN_KIND_WIRE = 1,
  CHAIN_KIND_ETHEREUM = 2,
  CHAIN_KIND_SOLANA = 3,
  CHAIN_KIND_SUI = 4,
}

/** sysio.opreg::OperatorStatus (enum, int32) */
export enum SysioOpregOperatorstatus {
  OPERATOR_STATUS_UNKNOWN = 0,
  OPERATOR_STATUS_WARMUP = 1,
  OPERATOR_STATUS_COOLDOWN = 2,
  OPERATOR_STATUS_ACTIVE = 3,
  OPERATOR_STATUS_TERMINATED = 240,
  OPERATOR_STATUS_SLASHED = 241,
}

/** sysio.opreg::OperatorType (enum, int32) */
export enum SysioOpregOperatortype {
  OPERATOR_TYPE_UNKNOWN = 0,
  OPERATOR_TYPE_PRODUCER = 1,
  OPERATOR_TYPE_BATCH = 2,
  OPERATOR_TYPE_UNDERWRITER = 3,
  OPERATOR_TYPE_CHALLENGER = 4,
}

/** sysio.opreg::TokenKind (enum, int32) */
export enum SysioOpregTokenkind {
  TOKEN_KIND_WIRE = 0,
  TOKEN_KIND_ETH = 256,
  TOKEN_KIND_ERC20 = 257,
  TOKEN_KIND_ERC721 = 258,
  TOKEN_KIND_ERC1155 = 259,
  TOKEN_KIND_LIQETH = 496,
  TOKEN_KIND_SOL = 512,
  TOKEN_KIND_LIQSOL = 752,
}

/** sysio.opreg::ChainAddress (type) */
export interface SysioOpregChainaddressType {
  kind: SysioOpregChainkind
  address: string
}

/** sysio.opreg::TokenAmount (type) */
export interface SysioOpregTokenamountType {
  kind: SysioOpregTokenkind
  amount: SysioOpregVarintInt64Type
}

/** sysio.opreg::op_config (type) */
export interface SysioOpregOpConfigType {
  req_prod_stakes: SysioOpregStakeRequirementType[]
  req_batchop_stakes: SysioOpregStakeRequirementType[]
  req_uw_stakes: SysioOpregStakeRequirementType[]
  max_available_producers: number
  max_available_batch_ops: number
  max_available_underwriters: number
  terminate_prune_delay_ms: number
}

/** sysio.opreg::operator_entry (type) */
export interface SysioOpregOperatorEntryType {
  account: string
  type: SysioOpregOperatortype
  status: SysioOpregOperatorstatus
  is_bootstrapped: boolean
  stakes: SysioOpregStakeEntryType[]
  registered_at: number
  available_at: number
  slashed_at: number
  terminated_at: number
}

/** sysio.opreg::processbatch (action) */
export interface SysioOpregProcessbatchAction {
  account: string
  was_eligible: boolean
  is_eligible: boolean
}

/** sysio.opreg::processprod (action) */
export interface SysioOpregProcessprodAction {
  account: string
  was_eligible: boolean
  is_eligible: boolean
}

/** sysio.opreg::processuw (action) */
export interface SysioOpregProcessuwAction {
  account: string
  was_eligible: boolean
  is_eligible: boolean
}

/** sysio.opreg::prune (action) */
export interface SysioOpregPruneAction {
}

/** sysio.opreg::regoperator (action) */
export interface SysioOpregRegoperatorAction {
  account: string
  type: SysioOpregOperatortype
  is_bootstrapped: boolean
}

/** sysio.opreg::setconfig (action) */
export interface SysioOpregSetconfigAction {
  max_available_producers: number
  max_available_batch_ops: number
  max_available_underwriters: number
  terminate_prune_delay_ms: number
}

/** sysio.opreg::slash (action) */
export interface SysioOpregSlashAction {
  account: string
  reason: string
}

/** sysio.opreg::stake (action) */
export interface SysioOpregStakeAction {
  account: string
  chain_addr: SysioOpregChainaddressType
  amount: SysioOpregTokenamountType
}

/** sysio.opreg::stake_entry (type) */
export interface SysioOpregStakeEntryType {
  chain_addr: SysioOpregChainaddressType
  amount: SysioOpregTokenamountType
  timestamp_ms: number
}

/** sysio.opreg::stake_requirement (type) */
export interface SysioOpregStakeRequirementType {
  chain_addr: SysioOpregChainaddressType
  min_amount: SysioOpregTokenamountType
  config_timestamp_ms: number
}

/** sysio.opreg::varint_int64 (type) */
export interface SysioOpregVarintInt64Type {
  value: number
}

// ── sysio.roa ──

/** sysio.roa::activateroa (action) */
export interface SysioRoaActivateroaAction {
  total_sys: string
  bytes_per_unit: number
}

/** sysio.roa::addpolicy (action) */
export interface SysioRoaAddpolicyAction {
  owner: string
  issuer: string
  net_weight: string
  cpu_weight: string
  ram_weight: string
  time_block: number
  network_gen: number
}

/** sysio.roa::expandpolicy (action) */
export interface SysioRoaExpandpolicyAction {
  owner: string
  issuer: string
  net_weight: string
  cpu_weight: string
  ram_weight: string
  network_gen: number
}

/** sysio.roa::extendpolicy (action) */
export interface SysioRoaExtendpolicyAction {
  owner: string
  issuer: string
  new_time_block: number
}

/** sysio.roa::finalizereg (action) */
export interface SysioRoaFinalizeregAction {
  owner: string
  status: number
}

/** sysio.roa::forcereg (action) */
export interface SysioRoaForceregAction {
  owner: string
  tier: number
}

/** sysio.roa::initnodereg (action) */
export interface SysioRoaInitnoderegAction {
  owner: string
}

/** sysio.roa::newuser (action) */
export interface SysioRoaNewuserAction {
  creator: string
  nonce: string
  pubkey: string
}

/** sysio.roa::nodeownerreg (type) */
export interface SysioRoaNodeownerregType {
  owner: string
  status: number
  trx_id: string
  trx_signature: string
  tier: number
  block_num: string
}

/** sysio.roa::nodeowners (type) */
export interface SysioRoaNodeownersType {
  owner: string
  tier: number
  total_sys: string
  allocated_sys: string
  allocated_bw: string
  allocated_ram: string
  network_gen: number
}

/** sysio.roa::policies (type) */
export interface SysioRoaPoliciesType {
  owner: string
  issuer: string
  net_weight: string
  cpu_weight: string
  ram_weight: string
  bytes_per_unit: number
  time_block: number
}

/** sysio.roa::reducepolicy (action) */
export interface SysioRoaReducepolicyAction {
  owner: string
  issuer: string
  net_weight: string
  cpu_weight: string
  ram_weight: string
  network_gen: number
}

/** sysio.roa::reslimit (type) */
export interface SysioRoaReslimitType {
  owner: string
  net_weight: string
  cpu_weight: string
  ram_bytes: number
}

/** sysio.roa::roa_state (type) */
export interface SysioRoaRoaStateType {
  is_active: boolean
  total_sys: string
  bytes_per_unit: number
  network_gen: number
}

/** sysio.roa::setbyteprice (action) */
export interface SysioRoaSetbytepriceAction {
  bytes_per_unit: number
}

/** sysio.roa::setpending (action) */
export interface SysioRoaSetpendingAction {
  owner: string
  tier: number
  trx_id: string
  block_num: string
  sig: string
}

/** sysio.roa::sponsor (type) */
export interface SysioRoaSponsorType {
  nonce: string
  username: string
}

/** sysio.roa::sponsorcount (type) */
export interface SysioRoaSponsorcountType {
  owner: string
  count: number
}

// ── sysio.system ──

/** sysio.system::trx_match_type (enum, uint8) */
export enum SysioSystemTrxMatchType {
  only = 0,
  first = 1,
  any = 2,
}

/** sysio.system::abi_hash (type) */
export interface SysioSystemAbiHashType {
  owner: string
  hash: string
}

/** sysio.system::actfinkey (action) */
export interface SysioSystemActfinkeyAction {
  finalizer_name: string
  finalizer_key: string
}

/** sysio.system::activate (action) */
export interface SysioSystemActivateAction {
  feature_digest: string
}

/** sysio.system::authority (type) */
export interface SysioSystemAuthorityType {
  threshold: number
  keys: SysioSystemKeyWeightType[]
  accounts: SysioSystemPermissionLevelWeightType[]
}

/** sysio.system::block_header (type) */
export interface SysioSystemBlockHeaderType {
  timestamp: number
  producer: string
  confirmed: number
  previous: string
  transaction_mroot: string
  action_mroot: string
  schedule_version: number
  new_producers?: SysioSystemProducerScheduleType | null
}

/** sysio.system::block_signing_authority_v0 (type) */
export interface SysioSystemBlockSigningAuthorityV0Type {
  threshold: number
  keys: SysioSystemKeyWeightType[]
}

/** sysio.system::blockchain_parameters (type) */
export interface SysioSystemBlockchainParametersType {
  max_block_net_usage: number
  target_block_net_usage_pct: number
  max_transaction_net_usage: number
  base_per_transaction_net_usage: number
  net_usage_leeway: number
  context_free_discount_net_usage_num: number
  context_free_discount_net_usage_den: number
  max_block_cpu_usage: number
  target_block_cpu_usage_pct: number
  max_transaction_cpu_usage: number
  min_transaction_cpu_usage: number
  max_transaction_lifetime: number
  max_transaction_delay: number
  max_inline_action_size: number
  max_inline_action_depth: number
  max_authority_depth: number
  max_action_return_value_size: number
  max_kv_key_size: number
  max_kv_value_size: number
  max_kv_secondary_key_size: number
}

/** sysio.system::deleteauth (action) */
export interface SysioSystemDeleteauthAction {
  account: string
  permission: string
  authorized_by: unknown
}

/** sysio.system::delfinkey (action) */
export interface SysioSystemDelfinkeyAction {
  finalizer_name: string
  finalizer_key: string
}

/** sysio.system::expandauth (action) */
export interface SysioSystemExpandauthAction {
  account: string
  permission: string
  keys: SysioSystemKeyWeightType[]
  accounts: SysioSystemPermissionLevelWeightType[]
}

/** sysio.system::fin_key_id_generator_info (type) */
export interface SysioSystemFinKeyIdGeneratorInfoType {
  next_finalizer_key_id: number
}

/** sysio.system::finalizer_auth_info (type) */
export interface SysioSystemFinalizerAuthInfoType {
  key_id: number
  fin_authority: SysioSystemFinalizerAuthorityType
}

/** sysio.system::finalizer_authority (type) */
export interface SysioSystemFinalizerAuthorityType {
  description: string
  weight: number
  public_key: string
}

/** sysio.system::finalizer_info (type) */
export interface SysioSystemFinalizerInfoType {
  finalizer_name: string
  active_key_id: number
  active_key_binary: string
  finalizer_key_count: number
}

/** sysio.system::finalizer_key_info (type) */
export interface SysioSystemFinalizerKeyInfoType {
  id: number
  finalizer_name: string
  finalizer_key: string
  finalizer_key_binary: string
}

/** sysio.system::init (action) */
export interface SysioSystemInitAction {
  version: number
  core: string
}

/** sysio.system::key_weight (type) */
export interface SysioSystemKeyWeightType {
  key: string
  weight: number
}

/** sysio.system::last_prop_finalizers_info (type) */
export interface SysioSystemLastPropFinalizersInfoType {
  last_proposed_finalizers: SysioSystemFinalizerAuthInfoType[]
}

/** sysio.system::limitauthchg (action) */
export interface SysioSystemLimitauthchgAction {
  account: string
  allow_perms: string[]
  disallow_perms: string[]
}

/** sysio.system::linkauth (action) */
export interface SysioSystemLinkauthAction {
  account: string
  code: string
  type: string
  requirement: string
  authorized_by: unknown
}

/** sysio.system::newaccount (action) */
export interface SysioSystemNewaccountAction {
  creator: string
  name: string
  owner: SysioSystemAuthorityType
  active: SysioSystemAuthorityType
}

/** sysio.system::onblock (action) */
export interface SysioSystemOnblockAction {
  header: SysioSystemBlockHeaderType
}

/** sysio.system::permission_level (type) */
export interface SysioSystemPermissionLevelType {
  actor: string
  permission: string
}

/** sysio.system::permission_level_weight (type) */
export interface SysioSystemPermissionLevelWeightType {
  permission: SysioSystemPermissionLevelType
  weight: number
}

/** sysio.system::producer_authority (type) */
export interface SysioSystemProducerAuthorityType {
  producer_name: string
  authority: unknown
}

/** sysio.system::producer_info (type) */
export interface SysioSystemProducerInfoType {
  owner: string
  producer_key: string
  rank: number
  is_active: boolean
  url: string
  unpaid_blocks: number
  last_claim_time: string
  location: number
  producer_authority: unknown
}

/** sysio.system::producer_key (type) */
export interface SysioSystemProducerKeyType {
  producer_name: string
  block_signing_key: string
}

/** sysio.system::producer_schedule (type) */
export interface SysioSystemProducerScheduleType {
  version: number
  producers: SysioSystemProducerKeyType[]
}

/** sysio.system::regfinkey (action) */
export interface SysioSystemRegfinkeyAction {
  finalizer_name: string
  finalizer_key: string
  proof_of_possession: string
}

/** sysio.system::regproducer (action) */
export interface SysioSystemRegproducerAction {
  producer: string
  producer_key: string
  url: string
  location: number
}

/** sysio.system::regproducer2 (action) */
export interface SysioSystemRegproducer2Action {
  producer: string
  producer_authority: unknown
  url: string
  location: number
}

/** sysio.system::rmvproducer (action) */
export interface SysioSystemRmvproducerAction {
  producer: string
}

/** sysio.system::setabi (action) */
export interface SysioSystemSetabiAction {
  account: string
  abi: string
  memo: unknown
}

/** sysio.system::setacctcpu (action) */
export interface SysioSystemSetacctcpuAction {
  account: string
  cpu_weight?: number | null
}

/** sysio.system::setacctnet (action) */
export interface SysioSystemSetacctnetAction {
  account: string
  net_weight?: number | null
}

/** sysio.system::setacctram (action) */
export interface SysioSystemSetacctramAction {
  account: string
  ram_bytes?: number | null
}

/** sysio.system::setalimits (action) */
export interface SysioSystemSetalimitsAction {
  account: string
  ram_bytes: number
  net_weight: number
  cpu_weight: number
}

/** sysio.system::setcode (action) */
export interface SysioSystemSetcodeAction {
  account: string
  vmtype: number
  vmversion: number
  code: string
  memo: unknown
}

/** sysio.system::setparams (action) */
export interface SysioSystemSetparamsAction {
  params: SysioSystemBlockchainParametersType
}

/** sysio.system::setpriv (action) */
export interface SysioSystemSetprivAction {
  account: string
  is_priv: number
}

/** sysio.system::setprodkeys (action) */
export interface SysioSystemSetprodkeysAction {
  schedule: SysioSystemProducerKeyType[]
}

/** sysio.system::setprods (action) */
export interface SysioSystemSetprodsAction {
  schedule: SysioSystemProducerAuthorityType[]
}

/** sysio.system::setram (action) */
export interface SysioSystemSetramAction {
  max_ram_size: number
}

/** sysio.system::setrank (action) */
export interface SysioSystemSetrankAction {
  producer: string
  rank: number
}

/** sysio.system::sysio_global_state (type) */
export interface SysioSystemSysioGlobalStateType {
  max_ram_size: number
  total_ram_bytes_reserved: number
  last_producer_schedule_update: string
  last_pervote_bucket_fill: string
  total_unpaid_blocks: number
  last_producer_schedule_size: number
}

/** sysio.system::unlinkauth (action) */
export interface SysioSystemUnlinkauthAction {
  account: string
  code: string
  type: string
  authorized_by: unknown
}

/** sysio.system::unregprod (action) */
export interface SysioSystemUnregprodAction {
  producer: string
}

/** sysio.system::updateauth (action) */
export interface SysioSystemUpdateauthAction {
  account: string
  permission: string
  parent: string
  auth: SysioSystemAuthorityType
  authorized_by: unknown
}

/** sysio.system::wasmcfg (action) */
export interface SysioSystemWasmcfgAction {
  settings: string
}

/** sysio.system::delpeerkey (action) */
export interface SysioSystemDelpeerkeyAction {
  proposer_finalizer_name: string
  key: string
}

/** sysio.system::getpeerkeys (action) */
export interface SysioSystemGetpeerkeysAction {
}

/** sysio.system::peer_key (type) */
export interface SysioSystemPeerKeyType {
  account: string
  data: unknown
}

/** sysio.system::peerkeys_t (type) */
export interface SysioSystemPeerkeysTType {
  producer_name: string
  peer_key?: string | null
}

/** sysio.system::regpeerkey (action) */
export interface SysioSystemRegpeerkeyAction {
  proposer_finalizer_name: string
  key: string
}

/** sysio.system::v0_data (type) */
export interface SysioSystemV0DataType {
  pubkey?: string | null
}

/** sysio.system::block_info_record (type) */
export interface SysioSystemBlockInfoRecordType {
  version: number
  block_height: number
  block_timestamp: string
}

/** sysio.system::addtrxp (action) */
export interface SysioSystemAddtrxpAction {
  receiver: string
  action_name: string
  match_type: SysioSystemTrxMatchType
  priority: number
}

/** sysio.system::deltrxp (action) */
export interface SysioSystemDeltrxpAction {
  priority: number
}

/** sysio.system::trx_prio (type) */
export interface SysioSystemTrxPrioType {
  priority: number
  receiver: string
  action_name: string
  match_type: SysioSystemTrxMatchType
}

/** sysio.system::trx_prio_global (type) */
export interface SysioSystemTrxPrioGlobalType {
  last_trx_priority_update: string
}

/** sysio.system::limit_auth_change (type) */
export interface SysioSystemLimitAuthChangeType {
  version: number
  account: string
  allow_perms: string[]
  disallow_perms: string[]
}

// ── sysio.token ──

/** sysio.token::account (type) */
export interface SysioTokenAccountType {
  balance: string
}

/** sysio.token::close (action) */
export interface SysioTokenCloseAction {
  owner: string
  symbol: string
}

/** sysio.token::create (action) */
export interface SysioTokenCreateAction {
  issuer: string
  maximum_supply: string
}

/** sysio.token::currency_stats (type) */
export interface SysioTokenCurrencyStatsType {
  supply: string
  max_supply: string
  issuer: string
}

/** sysio.token::issue (action) */
export interface SysioTokenIssueAction {
  to: string
  quantity: string
  memo: string
}

/** sysio.token::open (action) */
export interface SysioTokenOpenAction {
  owner: string
  symbol: string
  ram_payer: string
}

/** sysio.token::retire (action) */
export interface SysioTokenRetireAction {
  quantity: string
  memo: string
}

/** sysio.token::transfer (action) */
export interface SysioTokenTransferAction {
  from: string
  to: string
  quantity: string
  memo: string
}

// ── sysio.uwrit ──

/** sysio.uwrit::AttestationType (enum, int32) */
export enum SysioUwritAttestationtype {
  ATTESTATION_TYPE_UNSPECIFIED = 0,
  ATTESTATION_TYPE_OPERATOR_ACTION = 2001,
  ATTESTATION_TYPE_STAKE = 3001,
  ATTESTATION_TYPE_UNSTAKE = 3002,
  ATTESTATION_TYPE_PRETOKEN_PURCHASE = 3004,
  ATTESTATION_TYPE_PRETOKEN_YIELD = 3006,
  ATTESTATION_TYPE_RESERVE_BALANCE_SHEET = 43520,
  ATTESTATION_TYPE_STAKE_UPDATE = 60928,
  ATTESTATION_TYPE_NATIVE_YIELD_REWARD = 60929,
  ATTESTATION_TYPE_WIRE_TOKEN_PURCHASE = 60930,
  ATTESTATION_TYPE_CHALLENGE_RESPONSE = 60932,
  ATTESTATION_TYPE_SLASH_OPERATOR = 60933,
  ATTESTATION_TYPE_SWAP = 60934,
  ATTESTATION_TYPE_UNDERWRITE_INTENT = 60935,
  ATTESTATION_TYPE_UNDERWRITE_CONFIRM = 60936,
  ATTESTATION_TYPE_UNDERWRITE_REJECT = 60937,
  ATTESTATION_TYPE_UNDERWRITE_UNLOCK = 60938,
  ATTESTATION_TYPE_REMIT = 60944,
  ATTESTATION_TYPE_CHALLENGE_REQUEST = 60945,
  ATTESTATION_TYPE_EPOCH_SYNC = 60946,
  ATTESTATION_TYPE_ROSTER_UPDATE = 60947,
  ATTESTATION_TYPE_REMIT_CONFIRM = 60948,
  ATTESTATION_TYPE_BATCH_OPERATOR_NEXT_GROUP = 60943,
  ATTESTATION_TYPE_NODE_OWNER_REG = 60949,
  ATTESTATION_TYPE_STAKING_REWARD = 60950,
  ATTESTATION_TYPE_STAKE_RESULT = 60951,
  ATTESTATION_TYPE_ATTESTATION_PROCESSING_ERROR = 60952,
}

/** sysio.uwrit::ChainKind (enum, int32) */
export enum SysioUwritChainkind {
  CHAIN_KIND_UNKNOWN = 0,
  CHAIN_KIND_WIRE = 1,
  CHAIN_KIND_ETHEREUM = 2,
  CHAIN_KIND_SOLANA = 3,
  CHAIN_KIND_SUI = 4,
}

/** sysio.uwrit::TokenKind (enum, int32) */
export enum SysioUwritTokenkind {
  TOKEN_KIND_WIRE = 0,
  TOKEN_KIND_ETH = 256,
  TOKEN_KIND_ERC20 = 257,
  TOKEN_KIND_ERC721 = 258,
  TOKEN_KIND_ERC1155 = 259,
  TOKEN_KIND_LIQETH = 496,
  TOKEN_KIND_SOL = 512,
  TOKEN_KIND_LIQSOL = 752,
}

/** sysio.uwrit::UnderwriteRequestStatus (enum, int32) */
export enum SysioUwritUnderwriterequeststatus {
  UNDERWRITE_REQUEST_STATUS_PENDING = 0,
  UNDERWRITE_REQUEST_STATUS_CONFIRMED = 1,
  UNDERWRITE_REQUEST_STATUS_REJECTED = 2,
  UNDERWRITE_REQUEST_STATUS_COMPLETED = 3,
  UNDERWRITE_REQUEST_STATUS_EXPIRED = 4,
}

/** sysio.uwrit::UnderwriteStatus (enum, int32) */
export enum SysioUwritUnderwritestatus {
  UNDERWRITE_STATUS_INTENT_CREATED = 0,
  UNDERWRITE_STATUS_INTENT_SUBMITTED = 1,
  UNDERWRITE_STATUS_INTENT_CONFIRMED = 2,
  UNDERWRITE_STATUS_READY = 3,
  UNDERWRITE_STATUS_RELEASED = 5,
  UNDERWRITE_STATUS_SLASHED = 10,
}

/** sysio.uwrit::chain_kind_t (enum, uint8) */
export enum SysioUwritChainKindType {
  unknown = 0,
  wire = 1,
  ethereum = 2,
  solana = 3,
  sui = 4,
}

/** sysio.uwrit::ChainId (type) */
export interface SysioUwritChainidType {
  kind: SysioUwritChainkind
  id: SysioUwritVarintUint32Type
}

/** sysio.uwrit::TokenAmount (type) */
export interface SysioUwritTokenamountType {
  kind: SysioUwritTokenkind
  amount: SysioUwritVarintInt64Type
}

/** sysio.uwrit::collateral_entry (type) */
export interface SysioUwritCollateralEntryType {
  id: number
  underwriter: string
  chain_kind: SysioUwritChainKindType
  staked_amount: string
  locked_amount: string
  available_amount: string
}

/** sysio.uwrit::confirmuw (action) */
export interface SysioUwritConfirmuwAction {
  uw_entry_id: number
}

/** sysio.uwrit::createuwreq (action) */
export interface SysioUwritCreateuwreqAction {
  attestation_id: number
  type: SysioUwritAttestationtype
  data: string
}

/** sysio.uwrit::distfee (action) */
export interface SysioUwritDistfeeAction {
  uw_entry_id: number
}

/** sysio.uwrit::expirelock (action) */
export interface SysioUwritExpirelockAction {
  uw_entry_id: number
}

/** sysio.uwrit::locked_amount_t (type) */
export interface SysioUwritLockedAmountTType {
  chain_id: SysioUwritChainidType
  amount: SysioUwritTokenamountType
  lock_id: string
  lock_timestamp: number
}

/** sysio.uwrit::setconfig (action) */
export interface SysioUwritSetconfigAction {
  fee_bps: number
  confirm_lock_sec: number
  uw_fee_share_pct: number
  other_uw_share_pct: number
  batch_op_share_pct: number
}

/** sysio.uwrit::slash (action) */
export interface SysioUwritSlashAction {
  underwriter: string
  reason: string
}

/** sysio.uwrit::submituw (action) */
export interface SysioUwritSubmituwAction {
  underwriter: string
  msg_id: number
  source_sig: string
  target_sig: string
}

/** sysio.uwrit::underwriting_entry (type) */
export interface SysioUwritUnderwritingEntryType {
  id: number
  underwriter: string
  message_id: number
  status: SysioUwritUnderwritestatus
  source_amount: string
  target_amount: string
  source_chain: SysioUwritChainKindType
  target_chain: SysioUwritChainKindType
  intent_time: string
  unlock_time: string
  fee_earned: string
  source_sig: string
  target_sig: string
}

/** sysio.uwrit::updcltrl (action) */
export interface SysioUwritUpdcltrlAction {
  underwriter: string
  chain_kind: SysioUwritChainKindType
  amount: string
  is_increase: boolean
}

/** sysio.uwrit::uw_config (type) */
export interface SysioUwritUwConfigType {
  fee_bps: number
  confirm_lock_sec: number
  uw_fee_share_pct: number
  other_uw_share_pct: number
  batch_op_share_pct: number
}

/** sysio.uwrit::uw_request_t (type) */
export interface SysioUwritUwRequestTType {
  id: number
  type: SysioUwritAttestationtype
  status: SysioUwritUnderwriterequeststatus
  uw_name: string
  locked_amounts: SysioUwritLockedAmountTType[]
  unlock_timestamp: number
  released_timestamp: number
  slashed_timestamp: number
}

/** sysio.uwrit::varint_int64 (type) */
export interface SysioUwritVarintInt64Type {
  value: number
}

/** sysio.uwrit::varint_uint32 (type) */
export interface SysioUwritVarintUint32Type {
  value: number
}

// ── sysio.wrap ──

/** sysio.wrap::action (type) */
export interface SysioWrapActionType {
  account: string
  name: string
  authorization: SysioWrapPermissionLevelType[]
  data: string
}

/** sysio.wrap::exec (action) */
export interface SysioWrapExecAction {
  executer: string
  trx: SysioWrapTransactionType
}

/** sysio.wrap::extension (type) */
export interface SysioWrapExtensionType {
  type: number
  data: string
}

/** sysio.wrap::permission_level (type) */
export interface SysioWrapPermissionLevelType {
  actor: string
  permission: string
}

/** sysio.wrap::transaction (type) */
export interface SysioWrapTransactionType {
  context_free_actions: SysioWrapActionType[]
  actions: SysioWrapActionType[]
  transaction_extensions: SysioWrapExtensionType[]
}

/** sysio.wrap::transaction_header (type) */
export interface SysioWrapTransactionHeaderType {
  expiration: string
  ref_block_num: number
  ref_block_prefix: number
  max_net_usage_words: number
  max_cpu_usage_ms: number
  delay_sec: number
}

