#!/usr/bin/env zx

import { createRequire } from "node:module"

import { format } from "prettier"
import { $, fs, path } from "zx"

import {
  EthereumArtifactPackageName,
  PackageManifestPath,
  PackagePath,
  SolanaArtifactPackageName,
  assert,
  readJson
} from "./config.mjs"

const PackageRequire = createRequire(PackageManifestPath),
  EthereumManifestPath = PackageRequire.resolve(
    `${EthereumArtifactPackageName}/manifest.json`
  ),
  SolanaManifestPath = PackageRequire.resolve(
    `${SolanaArtifactPackageName}/manifest.json`
  ),
  EthereumOutputPath = path.join(
    PackagePath,
    "src/contracts/ethereum/generated"
  ),
  SolanaOutputPath = path.join(PackagePath, "src/programs/solana/generated"),
  ArtifactOutputPath = path.join(PackagePath, "src/artifacts/generated"),
  EthereumContractNames = [
    "OPP",
    "OPPInbound",
    "OperatorRegistry",
    "ReserveManager"
  ],
  SolanaProgramName = "liqsolCore",
  TypechainPath = path.join(PackagePath, "node_modules/.bin/typechain")

/** Resolve one exported file from a source-owned artifact package. */
function resolveArtifact(packageName, artifactPath) {
  return PackageRequire.resolve(`${packageName}/${artifactPath}`)
}

/** Format generated TypeScript according to repository rules. */
async function formatTypescript(source) {
  return format(source, {
    parser: "typescript",
    semi: false,
    singleQuote: false,
    trailingComma: "none"
  })
}

const [ethereumManifest, solanaManifest] = await Promise.all([
  readJson(EthereumManifestPath),
  readJson(SolanaManifestPath)
])

assert(
  ethereumManifest.package.name === EthereumArtifactPackageName,
  `Unexpected Ethereum artifact package ${ethereumManifest.package.name}`
)
assert(
  solanaManifest.package.name === SolanaArtifactPackageName,
  `Unexpected Solana artifact package ${solanaManifest.package.name}`
)
assert(
  EthereumContractNames.every(name => ethereumManifest.contracts[name] != null),
  "Ethereum artifact package does not cover the sdk-outpost contract surface"
)
assert(
  solanaManifest.programs[SolanaProgramName] != null,
  "Solana artifact package does not cover liqsol_core"
)

await Promise.all(
  [EthereumOutputPath, SolanaOutputPath, ArtifactOutputPath].map(outputPath =>
    fs.rm(outputPath, { force: true, recursive: true })
  )
)
await Promise.all(
  [SolanaOutputPath, ArtifactOutputPath].map(outputPath =>
    fs.mkdir(outputPath, { recursive: true })
  )
)

const ethereumInputs = EthereumContractNames.map(name =>
  resolveArtifact(
    EthereumArtifactPackageName,
    ethereumManifest.contracts[name].path
  )
)

await $({
  cwd: PackagePath
})`${TypechainPath} --target ethers-v5 --node16-modules --out-dir ${EthereumOutputPath} ${ethereumInputs}`

const { convertIdlToCamelCase } = PackageRequire(
    "@coral-xyz/anchor/dist/cjs/idl.js"
  ),
  solanaProgram = solanaManifest.programs[SolanaProgramName],
  rawIdl = await readJson(
    resolveArtifact(SolanaArtifactPackageName, solanaProgram.idlPath)
  ),
  idl = convertIdlToCamelCase(rawIdl),
  solanaSource = await formatTypescript(`
    /* Autogenerated file. Do not edit manually. */
    /* eslint-disable */
    import type { Idl } from "@coral-xyz/anchor"

    const liqsolCoreIdlValue = ${JSON.stringify(idl, null, 2)} as const

    /** Strict Anchor IDL type generated from the wire-solana artifact package. */
    export type LiqsolCore = Idl & Omit<typeof liqsolCoreIdlValue, "address">

    /** Camel-cased liqsol_core IDL consumed by Anchor's typed Program client. */
    export const liqsolCoreIdl = liqsolCoreIdlValue as LiqsolCore
  `),
  artifactSource = await formatTypescript(`
    /* Autogenerated file. Do not edit manually. */
    /* eslint-disable */

    /** Exact source-owned artifact manifests compiled into this SDK build. */
    export const OutpostArtifactManifests = ${JSON.stringify(
      {
        ethereum: ethereumManifest,
        solana: solanaManifest
      },
      null,
      2
    )} as const
  `)

await Promise.all([
  fs.writeFile(path.join(SolanaOutputPath, "LiqsolCore.ts"), solanaSource),
  fs.writeFile(
    path.join(SolanaOutputPath, "index.ts"),
    'export * from "./LiqsolCore.js"\n'
  ),
  fs.writeFile(path.join(ArtifactOutputPath, "Manifests.ts"), artifactSource),
  fs.writeFile(
    path.join(ArtifactOutputPath, "index.ts"),
    'export * from "./Manifests.js"\n'
  )
])

process.stdout.write(
  `Generated sdk-outpost clients from ${ethereumManifest.package.name}@${ethereumManifest.package.version} and ${solanaManifest.package.name}@${solanaManifest.package.version}\n`
)
